// The config-driven reader. ats.js (generated by tools/convert_ats_config.py)
// describes each ATS as data: url match patterns, fields that name the fact
// they take and the selectors and fill method that take it, the selectors
// that find custom questions and how to answer them, and the continue,
// submit and success paths. This file interprets that data for whichever
// ATS matches the page and exposes the same reader interface the
// hand-written readers do, plus a step model for forms that span pages.
(() => {
  if (window.__jtReader) return; // a hand-written reader owns this host
  const configs = window.__jtATS || [];
  const matchesPattern = (pattern, url) => {
    const re = new RegExp(
      "^" + pattern.split("*").map((s) => s.replace(/[.+?^${}()|[\]\\]/g, "\\$&")).join(".*") + "$",
    );
    return re.test(url);
  };
  const cfg = configs.find((c) => c.matches.some((m) => matchesPattern(m, location.href)));
  if (!cfg) return;

  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  const clean = (s) => (s || "").replace(/\s+/g, " ").replace(/[*✱]\s*$/, "").trim();
  const list = (x) => (Array.isArray(x) ? x : x ? [x] : []);

  // XPath with the table's placeholders: %INPUTPATH% is the field's own path,
  // %VALUE%, %UPPERVALUE% and %LOWERVALUE% are the value being filled.
  function expand(path, ctx) {
    return path
      .replaceAll("%INPUTPATH%", ctx.inputPath || "")
      .replaceAll("%UPPERVALUE%", (ctx.value || "").toUpperCase())
      .replaceAll("%LOWERVALUE%", (ctx.value || "").toLowerCase())
      .replaceAll("%VALUE%", ctx.value || "");
  }
  function $x(path, root = document) {
    const out = [];
    try {
      const it = document.evaluate(path, root, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
      for (let i = 0; i < it.snapshotLength; i++) out.push(it.snapshotItem(i));
    } catch (_) {
      // A selector the page's XPath engine rejects is a selector that
      // matches nothing.
    }
    return out;
  }
  const text = (node) => (node && node.nodeType === Node.TEXT_NODE ? node.textContent : node ? node.innerText || node.textContent : "");
  const visible = (el) => !!el && (el.nodeType !== Node.ELEMENT_NODE || el.offsetParent !== null || el.getClientRects().length > 0 || el.type === "file" || el.type === "hidden");
  function first(paths, ctx = {}, root = document) {
    for (const p of list(paths)) {
      const hit = $x(expand(p, ctx), root).find(visible);
      if (hit) return { el: hit, path: expand(p, ctx) };
    }
    return null;
  }

  // ---- fill methods, one per name the table uses ------------------------
  const events = (extra) => ({ bubbles: true, cancelable: true, ...(cfg.defaultEventOptions || {}), ...(extra || {}) });
  function setValue(el, value) {
    const proto = el.tagName === "TEXTAREA" ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
    const setter = Object.getOwnPropertyDescriptor(proto, "value")?.set;
    if (setter) setter.call(el, value);
    else el.value = value;
    el.setAttribute("value", value);
  }
  function typeInto(el, value, opts, blur) {
    const t = events(opts);
    el.dispatchEvent(new FocusEvent("focus", t));
    setValue(el, value);
    el.dispatchEvent(new CustomEvent("textInput", t));
    el.dispatchEvent(new InputEvent("input", t));
    el.dispatchEvent(new Event("change", t));
    if (blur) el.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  function clickOn(el, opts) {
    const t = events(opts);
    el.dispatchEvent(new FocusEvent("focus", t));
    el.dispatchEvent(new MouseEvent("mousedown", t));
    el.dispatchEvent(new MouseEvent("mouseup", t));
    if (typeof el.click === "function") el.click();
    else el.dispatchEvent(new MouseEvent("click", t));
    if (!(opts && opts.noBlur)) el.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  function chooseNative(el, value) {
    const wants = String(value).split("|").map((s) => s.trim().toLowerCase()).filter(Boolean);
    const opts = [...el.options];
    const opt =
      opts.find((o) => wants.includes(o.text.trim().toLowerCase()) || wants.includes(o.value.toLowerCase())) ||
      opts.find((o) => wants.some((w) => o.text.trim().toLowerCase().startsWith(w)));
    if (!opt) return false;
    const t = events();
    el.dispatchEvent(new FocusEvent("focus", t));
    el.value = opt.value;
    el.dispatchEvent(new InputEvent("input", t));
    el.dispatchEvent(new Event("change", t));
    el.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  function checkOrRadio(el, on) {
    const t = events();
    if (Boolean(el.checked) === Boolean(on)) return true;
    el.dispatchEvent(new FocusEvent("focus", t));
    if (el.type === "checkbox") el.click();
    else {
      el.dispatchEvent(new MouseEvent("click", t));
      el.checked = Boolean(on);
    }
    el.dispatchEvent(new InputEvent("input", t));
    el.dispatchEvent(new Event("change", t));
    el.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  function uploadFile(el, file) {
    if (!file) return false;
    const dt = new DataTransfer();
    dt.items.add(file);
    el.files = dt.files;
    el.dispatchEvent(new Event("change", events()));
    return true;
  }
  async function runMethod(method, el, value, file, opts) {
    const m = method || cfg.defaultMethod || "default";
    switch (m) {
      case "uploadResume":
        return uploadFile(el, file);
      case "click":
      case "reactClick":
        return clickOn(el, opts);
      case "selectCheckboxOrRadio":
        return checkOrRadio(el, true);
      case "clearValue":
        return typeInto(el, "", opts, false);
      case "blur":
        el.dispatchEvent(new FocusEvent("blur", events(opts)));
        return true;
      case "scrollListboxToOption":
        el.scrollIntoView({ block: "center" });
        return clickOn(el, { ...opts, noBlur: true });
      default: {
        const blur = m === "default";
        if (el.tagName === "SELECT") return chooseNative(el, value);
        if (el.type === "checkbox" || el.type === "radio") return checkOrRadio(el, true);
        if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") return typeInto(el, value, opts, blur);
        return clickOn(el, opts);
      }
    }
  }

  // The table's action list: each step waits up to `time` for its path,
  // skips itself on a failed `condition`, and either fires an event or
  // runs a method on what it found.
  async function runActions(actions, ctx, root, fallbackEl, value, file) {
    for (const a of actions || []) {
      if (a.delay) await sleep(a.delay);
      if (a.condition && !$x(expand(a.condition, ctx), root).length) continue;
      if (a.valueRequired && !value) continue;
      let target = a.path ? null : { el: fallbackEl, path: ctx.inputPath };
      const deadline = Date.now() + (a.time || 0);
      while (!target) {
        target = first(a.path, ctx, root);
        if (target || Date.now() >= deadline) break;
        await sleep(150);
      }
      if (!target) {
        if (a.allowFailure) continue;
        return false;
      }
      if (a.event) target.el.dispatchEvent(new Event(a.event, events(a.eventOptions)));
      else await runMethod(a.method || "click", target.el, value, file, a.eventOptions);
    }
    return true;
  }

  // ---- fields --------------------------------------------------------------
  // A field is one of the table's named facts with its variants, or a custom
  // question found by the question selectors.
  const KIND = (fact) =>
    fact === "resume" ? "file" : /^(work_authorized|needs_sponsorship|yes|consent)$/.test(fact || "") ? "yesno" : /^(gender|ethnicity|hispanic|veteran|disability|referral_source|country|state|degree)$/.test(fact || "") ? "select" : "text";

  function factFields() {
    const out = [];
    for (const f of cfg.fields) {
      const probe = first(f.variants.flatMap((v) => v.paths), { value: "" });
      const kind = KIND(f.fact);
      if (!probe) continue;
      out.push({ key: `fact:${f.name}`, label: f.name.replace(/_/g, " "), kind, required: false, options: [], fact: f.fact, _spec: f, _el: probe.el });
    }
    return out;
  }
  function questionFields(taken) {
    const out = [];
    for (const q of cfg.questions || []) {
      for (const box of list(q.fieldPath).flatMap((p) => $x(p))) {
        if (!visible(box)) continue;
        const input = list(q.inputPath).map((p) => $x(p, box)[0]).find(Boolean);
        const optionEls = list(q.optionsPath).flatMap((p) => $x(p, box));
        if (!input && !optionEls.length) continue;
        const anchor = input || optionEls[0];
        // A control a named fact already owns is not a question as well.
        if (taken.has(anchor) || optionEls.some((o) => taken.has(o))) continue;
        taken.add(anchor);
        const optionText = (o) => clean(list(q.optionsTextPath).map((p) => text($x(p, o)[0])).find((t) => t && t.trim()) || text(o) || o.value);
        let options = optionEls.map(optionText).filter(Boolean);
        // The question's label is the first candidate that is not one of its
        // own options; a group's option labels share the label selector.
        const label = clean(
          list(q.labelPath)
            .flatMap((p) => $x(p, box).map(text))
            .map(clean)
            .find((t) => t && !options.includes(t)),
        );
        if (!label) continue;
        let kind = "text";
        if (input && input.tagName === "TEXTAREA") kind = "long";
        else if (input && input.type === "file") kind = "file";
        else if (input && input.tagName === "SELECT") {
          kind = "select";
          options = [...input.options].map((o) => o.text.trim()).filter(Boolean);
        } else if (optionEls.length) kind = optionEls[0].type === "checkbox" ? "multiselect" : "select";
        else if (input && input.getAttribute("role") === "combobox") kind = "select";
        out.push({
          key: (input && (input.name || input.id)) || (optionEls[0] && optionEls[0].name) || `label:${label}`,
          label,
          kind,
          required: /[*✱]\s*$/.test(clean(box.innerText)),
          options,
          _q: q,
          _box: box,
          _el: input || null,
          _options: optionEls.map((el, i) => ({ el, text: options[i] || "" })),
        });
      }
    }
    return out;
  }
  async function read() {
    const facts = factFields();
    return [...facts, ...questionFields(new Set(facts.map((f) => f._el)))];
  }

  const optionLabel = (i) => clean(i.closest("label")?.innerText || document.querySelector(`label[for="${CSS.escape(i.id)}"]`)?.innerText || i.value);
  function current(field) {
    if (field._options && field._options.length) {
      const on = field._options.filter((o) => o.el.checked || o.el.getAttribute("aria-selected") === "true");
      if (on.length || !field._el) return on.map((o) => o.text).join(" | ");
    }
    const el = field._el;
    if (!el || !el.isConnected) return "";
    if (el.type === "file") return el.files && el.files.length ? el.files[0].name : "";
    if (el.tagName === "SELECT") return el.selectedOptions[0]?.text.trim() || "";
    if (el.type === "radio" || el.type === "checkbox") {
      const group = el.name ? [...document.querySelectorAll(`input[name="${CSS.escape(el.name)}"]`)] : [el];
      return group.filter((i) => i.checked).map(optionLabel).join(" | ");
    }
    return el.value || "";
  }

  async function fillSpec(spec, value, file) {
    const alternatives = String(value ?? "").split("|").map((s) => s.trim()).filter(Boolean);
    for (const want of alternatives.length ? alternatives : [""]) {
      for (const v of spec.variants) {
        const found = first(v.paths, { value: want });
        if (!found) continue;
        const ok = await runMethod(v.method, found.el, want, file, v.eventOptions);
        const acted = await runActions(v.actions, { inputPath: found.path, value: want }, document, found.el, want, file);
        if (ok && acted) return true;
      }
    }
    return false;
  }

  async function fill(field, value, file) {
    if (field._spec) return fillSpec(field._spec, value, file);
    const wants = String(value ?? "").split("|").map((s) => s.trim()).filter(Boolean);
    if (field._q && field._q.fillActions && field._options?.length && !field._el?.tagName?.match(/SELECT|TEXTAREA/)) {
      // A custom choice with its own recipe: open the list, click the option.
      for (const want of wants) {
        if (await runActions(field._q.fillActions, { value: want }, field._box, field._el, want, file)) {
          await sleep(200);
          if (current(field)) return true;
        }
      }
    }
    if (field._options && field._options.length && field._options[0].el.type) {
      let took = false;
      for (const o of field._options) {
        if (wants.map((w) => w.toLowerCase()).includes(o.text.toLowerCase()) && !o.el.checked) {
          checkOrRadio(o.el, true);
          took = true;
          if (o.el.type === "radio") break;
        }
      }
      if (took) return true;
    }
    const el = field._el;
    if (!el || !el.isConnected) return false;
    if (field.kind === "file") return uploadFile(el, file);
    if (el.tagName === "SELECT") return chooseNative(el, value);
    if (el.type === "radio" || el.type === "checkbox") return checkOrRadio(el, true);
    return typeInto(el, wants[0] ?? "", null, cfg.defaultMethod === "default");
  }

  const nextButton = () => first(cfg.continue || [])?.el || null;
  const submitButton = () => first(cfg.submit || [])?.el || null;
  const submitted = () => (cfg.success || []).some((p) => $x(p).length > 0);
  const anyField = () =>
    !!first(cfg.fields.flatMap((f) => f.variants.flatMap((v) => v.paths)), { value: "" }) ||
    (cfg.questions || []).some((q) => list(q.fieldPath).some((p) => $x(p).some(visible)));

  window.__jtReader = {
    host: cfg.name.toLowerCase(),
    ready: anyField,
    read,
    fill,
    current,
    submitButton,
    nextButton,
    submitted,
    proxySubmit: !!cfg.proxySubmit,
  };
})();
