// The config-driven reader. extension/ats/<ATS>.js (generated by
// tools/convert_ats_config.py) describes one ATS as data: url match
// patterns, fields that name the fact they take and the selectors and fill
// method that take it, repeated groups (education, experience) with an add
// button and nested fields, flow steps (open the form, expand a section,
// save it), the selectors that find custom questions and how to answer
// them, and the apply, continue, submit and success paths. This file
// interprets that data for the matching ATS and exposes the same reader
// interface the hand-written readers do, plus a step model for forms that
// span pages.
(() => {
  if (window.__jtReader) return; // a hand-written reader owns this host
  const configs = window.__jtATS || [];

  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  const clean = (s) => (s || "").replace(/\s+/g, " ").replace(/[*✱]\s*$/, "").trim();
  const list = (x) => (Array.isArray(x) ? x : x ? [x] : []);
  const matchesPattern = (pattern, url) => {
    const re = new RegExp(
      "^" + pattern.split("*").map((s) => s.replace(/[.+?^${}()|[\]\\]/g, "\\$&")).join(".*") + "$",
    );
    return re.test(url);
  };

  // XPath with the table's placeholders: %INPUTPATH% is the field's own
  // path, %VALUE% and its cases the value being filled, %NUMBER0% and
  // %INDEX0% the entry of a repeated group, one- and zero-based.
  function expand(path, ctx) {
    const v = String(ctx.value ?? "");
    const raw = String(ctx.raw ?? v);
    return path
      .replaceAll("%INPUTPATH%", ctx.inputPath || "")
      .replaceAll("%UPPERUNMAPPEDVALUE%", raw.toUpperCase())
      .replaceAll("%LOWERUNMAPPEDVALUE%", raw.toLowerCase())
      .replaceAll("%UNMAPPEDVALUE%", raw)
      .replaceAll("%UPPERVALUE%", v.toUpperCase())
      .replaceAll("%LOWERVALUE%", v.toLowerCase())
      .replaceAll("%VALUE%", v)
      .replaceAll("%NUMBER0%", String((ctx.index ?? 0) + 1))
      .replaceAll("%INDEX0%", String(ctx.index ?? 0))
      .replaceAll("%LENGTHPLUSONE0%", String((ctx.length ?? 0) + 1));
  }
  function $x(path, root = document) {
    const out = [];
    try {
      const it = document.evaluate(path, root, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
      for (let i = 0; i < it.snapshotLength; i++) out.push(it.snapshotItem(i));
    } catch (_) {
      // A selector the page's XPath engine rejects is a selector that
      // matches nothing.
    }
    return out;
  }
  const text = (node) => (node && node.nodeType === Node.TEXT_NODE ? node.textContent : node ? node.innerText || node.textContent : "");
  const visible = (el) => !!el && (el.nodeType !== Node.ELEMENT_NODE || el.offsetParent !== null || el.getClientRects().length > 0 || el.type === "file" || el.type === "hidden");
  // A variant marked hidden may fill an element the page does not show (a
  // radio behind a styled label); everything else must be visible.
  function first(paths, ctx = {}, root = document, allowHidden = false) {
    for (const p of list(paths)) {
      const hit = $x(expand(p, ctx), root).find((el) => allowHidden || visible(el));
      if (hit) return { el: hit, path: expand(p, ctx) };
    }
    return null;
  }
  async function waitFirst(paths, ctx, root, allowHidden, ms) {
    const deadline = Date.now() + (ms || 0);
    for (;;) {
      const hit = first(paths, ctx, root, allowHidden);
      if (hit || Date.now() >= deadline) return hit;
      await sleep(150);
    }
  }
  // Nested lists of paths: every path in an inner list must match for the
  // inner list to count, any inner list matching is a match.
  const anyGroup = (groups) => list(groups).some((g) => list(g).length && list(g).every((p) => $x(p).length));

  // The config for this page: by url, or by the marks an embedded form
  // leaves on a host of its own (an iframe or a form posting to the ATS).
  // A url the table excludes (a confirmation page, a listing) gets nothing.
  const cfg =
    configs.find((c) => c.matches.some((m) => matchesPattern(m, location.href))) ||
    configs.find((c) => anyGroup(c.embeddedPaths));
  if (!cfg) return;
  if (list(cfg.urlsExcluded).some((g) => matchesPattern(g, location.href))) return;

  // Fields live inside the container when the table says so (a Greenhouse
  // form beside a job board, a Workday frame beside its chrome).
  const container = () => first(cfg.container || [], {}, document, true)?.el || null;
  const scope = () => container() || (cfg.containerRequired ? null : document);

  // ---- fill methods, one per name the table uses ---------------------------
  const events = (extra) => ({ bubbles: true, cancelable: true, ...(cfg.defaultEventOptions || {}), ...(extra || {}) });
  // Only an input or a textarea takes a value; a button or a div found by
  // a selector meant for one throws "Illegal invocation" from the native
  // setter (Workday's experience page, report 8), which aborted the fill.
  const takesValue = (el) => !!el && (el.tagName === "INPUT" || el.tagName === "TEXTAREA" || el.isContentEditable);
  function setValue(el, value) {
    if (!takesValue(el)) return false;
    if (el.isContentEditable && el.tagName !== "INPUT" && el.tagName !== "TEXTAREA") {
      el.textContent = value;
      return true;
    }
    const proto = el.tagName === "TEXTAREA" ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
    const setter = Object.getOwnPropertyDescriptor(proto, "value")?.set;
    if (setter) setter.call(el, value);
    else el.value = value;
    el.setAttribute("value", value);
    return true;
  }
  function typeInto(el, value, opts, blur) {
    if (!takesValue(el)) return false;
    const t = events(opts);
    el.dispatchEvent(new FocusEvent("focus", t));
    setValue(el, value);
    el.dispatchEvent(new CustomEvent("textInput", t));
    el.dispatchEvent(new InputEvent("input", t));
    el.dispatchEvent(new Event("change", t));
    if (blur) el.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  // A search box behind a picker (Workday's selectinput, any input that
  // says Search or is a combobox) filters on keystrokes, not on a value
  // that appears whole: measured 2026-09-08 on Workday's country-code
  // search, a set value with one input event and Enter left the list
  // unfiltered, while the same text typed one character at a time with key
  // events, a short pause and Enter filtered it and selected the match.
  const isSearchInput = (el) =>
    !!el &&
    el.tagName === "INPUT" &&
    (el.getAttribute("data-uxi-widget-type") === "selectinput" ||
      /search/i.test(el.getAttribute("placeholder") || "") ||
      el.getAttribute("role") === "combobox" ||
      el.getAttribute("aria-autocomplete") === "list");
  async function typeSlowly(el, value, opts) {
    const t = events(opts);
    // The click that opens the widget and puts the caret in the box: the
    // recipe's own click lands on the field's frame, and the measured
    // sequence clicked the input itself (captures 16 to 20).
    if (document.querySelector('[data-automation-activepopup="true"], [class*="select__menu"]')) {
      // A list left open by the step before would take the keystrokes.
      (document.activeElement || document.body).dispatchEvent(new KeyboardEvent("keydown", { ...t, key: "Escape", code: "Escape", keyCode: 27, which: 27 }));
      await sleep(300);
    }
    el.focus();
    el.dispatchEvent(new FocusEvent("focus", t));
    if (typeof el.click === "function") el.click();
    await sleep(300);
    note(`typing "${String(value).slice(0, 30)}" into ${el.id || el.name || "search"} one key at a time`);
    setValue(el, "");
    el.dispatchEvent(new InputEvent("input", { ...t, inputType: "deleteContentBackward" }));
    let typed = "";
    for (const ch of String(value ?? "")) {
      el.dispatchEvent(new KeyboardEvent("keydown", { ...t, key: ch }));
      el.dispatchEvent(new KeyboardEvent("keypress", { ...t, key: ch }));
      typed += ch;
      setValue(el, typed);
      el.dispatchEvent(new InputEvent("input", { ...t, data: ch, inputType: "insertText" }));
      el.dispatchEvent(new KeyboardEvent("keyup", { ...t, key: ch }));
      await sleep(60);
    }
    // The search needs a moment before Enter; measured at 700 ms on
    // Workday's country-code box, 400 was not enough for the field of study.
    await sleep(900);
    return true;
  }
  // An event of the class its name implies: a recipe's "keydown" with
  // key Enter must be a KeyboardEvent carrying the key, or the page sees
  // a key press with no key (capture 25: Workday's field-of-study search
  // never filtered because its Enter arrived as a bare Event).
  function eventOf(name, init) {
    if (/^key/.test(name)) return new KeyboardEvent(name, init);
    if (/^(mouse|click|dblclick|contextmenu)/.test(name)) return new MouseEvent(name, init);
    if (/^pointer/.test(name)) return new PointerEvent(name, init);
    if (/^(focus|blur)/.test(name)) return new FocusEvent(name, init);
    if (name === "input" || name === "beforeinput") return new InputEvent(name, init);
    return new Event(name, init);
  }
  function clickOn(el, opts) {
    const t = events(opts);
    el.dispatchEvent(new FocusEvent("focus", t));
    el.dispatchEvent(new MouseEvent("mousedown", t));
    el.dispatchEvent(new MouseEvent("mouseup", t));
    if (typeof el.click === "function") el.click();
    else el.dispatchEvent(new MouseEvent("click", t));
    if (!(opts && opts.noBlur)) el.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  function chooseOption(opt) {
    const sel = opt.closest("select");
    if (!sel) return clickOn(opt, { noBlur: true });
    const t = events();
    sel.dispatchEvent(new FocusEvent("focus", t));
    sel.value = opt.value;
    sel.dispatchEvent(new InputEvent("input", t));
    sel.dispatchEvent(new Event("change", t));
    sel.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  function chooseNative(el, value) {
    const wants = String(value).split("|").map((s) => s.trim().toLowerCase()).filter(Boolean);
    const opts = [...el.options];
    const opt =
      opts.find((o) => wants.includes(o.text.trim().toLowerCase()) || wants.includes(o.value.toLowerCase())) ||
      opts.find((o) => wants.some((w) => o.text.trim().toLowerCase().startsWith(w)));
    return opt ? chooseOption(opt) : false;
  }
  // An option element the table pointed at: a native <option> is chosen
  // through its select, anything else (a listbox row) is clicked.
  const pickOption = (el) => (el.tagName === "OPTION" ? chooseOption(el) : clickOn(el, { noBlur: true }));
  function checkOrRadio(el, on) {
    const t = events();
    if (Boolean(el.checked) === Boolean(on)) return true;
    el.dispatchEvent(new FocusEvent("focus", t));
    if (el.type === "checkbox") el.click();
    else {
      el.dispatchEvent(new MouseEvent("click", t));
      el.checked = Boolean(on);
    }
    el.dispatchEvent(new InputEvent("input", t));
    el.dispatchEvent(new Event("change", t));
    el.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  function uploadFile(el, file) {
    if (!file) return false;
    const dt = new DataTransfer();
    dt.items.add(file);
    el.files = dt.files;
    el.dispatchEvent(new Event("change", events()));
    return true;
  }
  // A rich-text editor hides its textarea behind an iframe named after it;
  // the page's editor object is out of a content script's reach, so the
  // editable body is written directly and the textarea kept in step.
  function richText(el, value) {
    const frame = document.getElementById(`${el.id}_ifr`) || el.parentElement?.querySelector("iframe");
    const body = frame?.contentDocument?.body;
    if (body) {
      body.innerHTML = String(value ?? "")
        .split(/\n{2,}/)
        .map((p) => `<p>${p.replace(/\n/g, "<br>")}</p>`)
        .join("");
      body.dispatchEvent(new InputEvent("input", { bubbles: true }));
      body.dispatchEvent(new Event("change", { bubbles: true }));
    }
    setValue(el, value);
    el.dispatchEvent(new Event("change", events()));
    return true;
  }
  async function runMethod(method, el, value, file, opts) {
    const m = method || cfg.defaultMethod || "default";
    switch (m) {
      case "uploadResume":
        return uploadFile(el, file);
      case "click":
      case "reactClick":
        return clickOn(el, opts);
      case "selectCheckboxOrRadio":
        return checkOrRadio(el, true);
      case "clearValue":
        return typeInto(el, "", opts, false);
      case "setValueOnly":
        setValue(el, value);
        return true;
      case "vanillaWithBlur":
        return typeInto(el, value, opts, true);
      case "ui5": {
        // A UI5 input commits on Enter and on focus leaving, and reads the
        // value back off the element on both.
        typeInto(el, value, opts, false);
        el.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", code: "Enter", keyCode: 13, bubbles: true }));
        el.dispatchEvent(new KeyboardEvent("keyup", { key: "Enter", code: "Enter", keyCode: 13, bubbles: true }));
        el.dispatchEvent(new FocusEvent("blur", events(opts)));
        el.dispatchEvent(new FocusEvent("focusout", events(opts)));
        return true;
      }
      case "tinyMCE":
        return richText(el, value);
      case "blur":
        el.dispatchEvent(new FocusEvent("blur", events(opts)));
        return true;
      case "scrollListboxToOption":
        el.scrollIntoView({ block: "center" });
        return clickOn(el, { ...opts, noBlur: true });
      case "reactDatePickerMonth": {
        // A month picker fed by typing: the value, then Enter, then away.
        typeInto(el, value, opts, false);
        el.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", code: "Enter", keyCode: 13, bubbles: true }));
        await sleep(150);
        el.dispatchEvent(new FocusEvent("blur", events(opts)));
        return true;
      }
      default: {
        const blur = m === "default";
        if (el.tagName === "SELECT") return chooseNative(el, value);
        if (el.type === "checkbox" || el.type === "radio") return checkOrRadio(el, true);
        if (isSearchInput(el) && value) return typeSlowly(el, value, opts);
        if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") return typeInto(el, value, opts, blur);
        return clickOn(el, opts);
      }
    }
  }

  // ---- values --------------------------------------------------------------
  // A `values` map in the table names answers by code and lists the option
  // texts each code may appear as; our text picks the code whose texts it
  // matches, and those texts are tried in turn. A map named by a string
  // (a country or state abbreviation table) is not carried, so the value
  // stands as it is.
  function mapValues(values, ours) {
    if (!values || typeof values !== "object" || !ours) return [ours];
    const low = ours.toLowerCase();
    for (const texts of Object.values(values)) {
      const options = list(texts).map(String);
      if (options.some((t) => t.toLowerCase() === low || low.startsWith(t.toLowerCase()) || t.toLowerCase().startsWith(low))) {
        return [...new Set([ours, ...options])];
      }
    }
    return [ours];
  }
  const YES = /^(yes|true|y)\b/i;
  const NO = /^(no|false|n)\b/i;
  // A `valuePathMap` names a path per value: the radio for "African
  // American", the box for "true". Ours picks the key it means.
  function mapPath(valuePathMap, ours) {
    const low = String(ours ?? "").toLowerCase();
    const keys = Object.keys(valuePathMap);
    const key =
      keys.find((k) => k.toLowerCase() === low) ||
      keys.find((k) => low && (low.startsWith(k.toLowerCase()) || k.toLowerCase().startsWith(low))) ||
      (YES.test(low) ? keys.find((k) => /^(true|yes)$/i.test(k)) : null) ||
      (NO.test(low) ? keys.find((k) => /^(false|no)$/i.test(k)) : null);
    return key ? valuePathMap[key] : null;
  }
  // The value an action or variant asks for by name: a group entry's own
  // attribute inside a group, a date for today's-date names, otherwise a
  // scalar the profile carries under that name.
  function factValue(key, ctx) {
    if (ctx.item) {
      const v = entryValue(key, ctx.item, ctx.fact);
      if (v !== null && v !== "") return v;
    }
    if (/^(current_date|disability_date|today)/.test(key)) return formatDate(key, todayParts());
    const p = window.__jtProfile || {};
    return typeof p[key] === "string" || typeof p[key] === "number" ? String(p[key]) : null;
  }
  // The candidates an action or variant fills with: its own constant, the
  // fact it names, or the field's value, through its own values map.
  function candidates(spec, ctx, value) {
    let v = value;
    if (spec.valueKey) v = factValue(spec.valueKey, ctx) ?? v;
    if (spec.value !== undefined) v = spec.value === true ? "true" : spec.value === false ? "false" : spec.value;
    if (Array.isArray(v)) return v.map(String).filter(Boolean);
    const s = v == null ? "" : String(v);
    return s ? mapValues(spec.values, s) : [""];
  }

  // The table's action list: each step waits up to `time` for its path,
  // skips itself on a failed `condition` or an empty value it needs, and
  // either fires an event, waits for its path to be removed, picks the
  // option its `valuePath` names, or runs a method on what it found.
  let trace = null;
  const note = (msg) => {
    if (trace) trace.push(msg);
  };
  let seenOptions = null;

  // The closest option on screen to a value, for a picker whose list is a
  // search the table matches by string: Workday spells a school its own
  // way ("Pennsylvania State University-Main Campus"), a degree list may
  // not carry "Bachelor of Science" as written, a field of study may only
  // offer "Applied Mathematics". Tokens of the value (stems of five
  // letters, stop words dropped) are looked for in each option; the part
  // of the value after a comma is a preference, not a requirement, so
  // "..., University Park" picks that campus among several. Close enough
  // is most of the tokens present; ties go to the shorter option.
  const STOP = new Set(["the", "of", "and", "at", "in", "a", "an"]);
  const stems = (t) =>
    String(t || "")
      .toLowerCase()
      .replace(/[^a-z0-9 ]+/g, " ")
      .split(/\s+/)
      .filter((w) => w && !STOP.has(w))
      .map((w) => w.slice(0, 5));
  function closest(options, value) {
    const [main, ...rest] = String(value || "").split(",");
    const want = stems(main);
    const prefer = stems(rest.join(" "));
    if (!want.length) return null;
    let best = null;
    for (const el of options) {
      const label = shownLabel(el);
      const have = new Set(stems(label));
      const hit = want.filter((w) => have.has(w)).length / want.length;
      if (hit < 0.6) continue;
      const bonus = prefer.length ? prefer.filter((w) => have.has(w)).length / prefer.length : 0;
      const score = hit + bonus * 0.5;
      if (!best || score > best.score || (score === best.score && label.length < best.label.length)) best = { el, label, score };
    }
    return best;
  }
  // An option's text: its own, or the label attribute Workday puts on the
  // option itself or on a child (capture 14: 45 options read as empty and
  // none could score).
  const shownLabel = (el) =>
    clean(
      text(el) ||
        el.getAttribute("data-automation-label") ||
        el.getAttribute("aria-label") ||
        el.querySelector("[data-automation-label]")?.getAttribute("data-automation-label") ||
        "",
    );
  const OPTION_SELECTORS = '[role="option"], [data-automation-id="promptLeafNode"], [data-automation-id="promptOption"], [class*="select__option"], li[role="menuitem"]';
  // The options of the popup that is open now, not every option on the
  // page: with the degree list still open, the field-of-study fallback
  // clicked "Master of Computer Science" into the degree (capture 23).
  const POPUP_SELECTORS = '[data-automation-activepopup="true"], [data-automation-id="activeListContainer"], [class*="select__menu"], [role="listbox"]';
  const optionsOnScreen = () => {
    const popups = [...document.querySelectorAll(POPUP_SELECTORS)].filter(visible);
    const scope = popups.length ? popups[popups.length - 1] : null;
    return scope ? [...scope.querySelectorAll(OPTION_SELECTORS)].filter(visible) : [];
  };
  async function runActions(actions, ctx, root, fallbackEl, value, file) {
    for (const [i, a] of (actions || []).entries()) {
      if (a.delay) await sleep(a.delay);
      if (a.condition && !list(a.condition).some((c) => $x(expand(c, ctx), root).length)) continue;
      const cands = candidates(a, ctx, value);
      const have = cands.some(Boolean);
      if ((a.skipOnEmptyValue || a.valueRequired) && !have) continue;
      const actx = { ...ctx, value: cands[0] || "" };
      if (a.removed) {
        const deadline = Date.now() + (a.removedTime || a.time || 1000);
        while (Date.now() < deadline && first(a.path || ["."], actx, root, true)) await sleep(100);
        continue;
      }
      let target = a.path ? null : { el: fallbackEl, path: ctx.inputPath };
      if (!target) target = await waitFirst(a.path, actx, root, a.hidden === true, a.time || 0);
      const picksOption = list(a.path).some((p) => /%(UPPER|LOWER)?(UNMAPPED)?VALUE%/.test(p) && /option|promptLeafNode|promptOption|listbox/i.test(p));
      if (!target && picksOption) {
        const shown = optionsOnScreen();
        const best = closest(shown, ctx.raw ?? actx.value);
        if (best) {
          note(`action ${i}: closest option "${best.label}" for "${actx.value}"`);
          target = { el: best.el, path: "closest" };
        } else if (shown.length) {
          seenOptions = [...new Set(shown.map(shownLabel).filter(Boolean))].slice(0, 60);
          note(`action ${i}: ${shown.length} options shown, none close to "${actx.value}": ${seenOptions.slice(0, 6).join(" / ")}`);
        }
      }
      if (!target) {
        if (a.allowFailure) continue;
        note(`action ${i} (${a.method || a.event || "path"}): nothing at its path for "${actx.value}"`);
        return false;
      }
      if (a.event) {
        target.el.dispatchEvent(eventOf(a.event, events(a.eventOptions)));
        continue;
      }
      if (a.valuePath) {
        let picked = false;
        for (const cand of cands) {
          const opt = await waitFirst(a.valuePath, { ...ctx, inputPath: target.path, value: cand, raw: value }, root, true, a.valueElementTime || 300);
          if (opt) {
            picked = pickOption(opt.el);
            break;
          }
        }
        if (!picked && !a.allowFailure) {
          note(`action ${i}: no option for "${cands.join(" | ")}"`);
          return false;
        }
        continue;
      }
      await runMethod(a.method || "click", target.el, cands[0] ?? "", file, a.eventOptions);
    }
    return true;
  }

  // ---- dates and entry values for repeated groups --------------------------
  const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
  function parseDate(s) {
    if (!s) return null;
    const t = String(s).trim();
    let m = t.match(/^(\d{4})-(\d{1,2})(?:-(\d{1,2}))?/);
    if (m) return { y: +m[1], m: +m[2], d: +(m[3] || 1) };
    m = t.match(/^(\d{1,2})\/(?:(\d{1,2})\/)?(\d{4})$/);
    if (m) return { y: +m[3], m: +m[1], d: +(m[2] || 1) };
    m = t.match(/^([A-Za-z]{3,9})\.?\s+(\d{4})$/);
    if (m) {
      const idx = MONTHS.findIndex((n) => n.toLowerCase().startsWith(m[1].slice(0, 3).toLowerCase()));
      if (idx >= 0) return { y: +m[2], m: idx + 1, d: 1 };
    }
    m = t.match(/^(\d{4})$/);
    if (m) return { y: +m[1], m: 1, d: 1 };
    return null;
  }
  const todayParts = () => {
    const n = new Date();
    return { y: n.getFullYear(), m: n.getMonth() + 1, d: n.getDate() };
  };
  const pad = (n) => String(n).padStart(2, "0");
  // The table names a date field by the format it takes; a name with no
  // format takes a month and year for a start or end, a full date for
  // today's date or a birthday.
  function formatDate(name, d) {
    if (!d) return null;
    if (/month_text/.test(name)) return MONTHS[d.m - 1];
    if (/month_abbr/.test(name)) return MONTHS[d.m - 1].slice(0, 3);
    if (/_month$/.test(name)) return `${d.m} | ${pad(d.m)} | ${MONTHS[d.m - 1]}`;
    if (/_(year|YYYY)$/.test(name)) return String(d.y);
    if (/_(day|D)$/.test(name)) return String(d.d);
    if (/_DD$/.test(name)) return pad(d.d);
    if (/_M$/.test(name)) return String(d.m);
    if (/slashes_MMDDYYYY|_MMDDYYYY$/.test(name)) return `${pad(d.m)}/${pad(d.d)}/${d.y}`;
    if (/slashes_MDDYY/.test(name)) return `${d.m}/${pad(d.d)}/${String(d.y).slice(-2)}`;
    if (/slashes_MDYYYY/.test(name)) return `${d.m}/${d.d}/${d.y}`;
    if (/slashes_MMYYYY|_MMYYYY$/.test(name)) return `${pad(d.m)}/${d.y}`;
    if (/dashes_YYYYMMDD/.test(name)) return `${d.y}-${pad(d.m)}-${pad(d.d)}`;
    if (/dashes_YYYYMM/.test(name)) return `${d.y}-${pad(d.m)}`;
    if (/dashes_MMMYYYY/.test(name)) return `${MONTHS[d.m - 1].slice(0, 3)}-${d.y}`;
    if (/dashes_MMYYYY/.test(name)) return `${pad(d.m)}-${d.y}`;
    if (/month_DD_comma_YYYY/.test(name)) return `${MONTHS[d.m - 1]} ${pad(d.d)}, ${d.y}`;
    if (/_MM$/.test(name)) return pad(d.m);
    if (/^(current_date|disability_date|today|birthday)/.test(name)) return `${pad(d.m)}/${pad(d.d)}/${d.y}`;
    return `${pad(d.m)}/${d.y}`;
  }
  // What a nested field takes from one profile row, by the table's name for
  // it. null means the field is not ours to fill for this row.
  function entryValue(name, item, fact) {
    const start = parseDate(item.start);
    const end = parseDate(item.end);
    const now = new Date();
    if (/^(start|begin)/.test(name)) return formatDate(name, start);
    if (/^(grad|end|actual_completion)/.test(name)) return item.current ? null : formatDate(name, end);
    switch (name) {
      case "education":
      case "school":
      case "name":
        return fact === "education" ? item.school : item.company;
      case "major":
      case "field":
        return item.field || null;
      case "degree":
        return item.degree || null;
      case "gpa":
        return item.gpa || null;
      case "graduated":
      case "did_graduate":
      case "qualification_complete":
        return end && new Date(end.y, end.m - 1, 1) <= now ? "Yes" : "No";
      case "title":
        return item.title || null;
      case "company":
      case "employer":
        return item.company || null;
      case "location":
      case "city_state":
      case "city_state_full":
        return item.location || null;
      case "city":
        return item.location ? item.location.split(",")[0].trim() : null;
      case "state":
        return item.location && item.location.includes(",") ? item.location.split(",")[1].trim() : null;
      case "country":
        return item.location && item.location.split(",").length > 2 ? item.location.split(",").pop().trim() : null;
      case "description":
        return item.description || null;
      case "description_stripped":
        return item.description ? item.description.replace(/\s+/g, " ").trim() : null;
      case "currently_working":
        return item.current ? "Yes" : null;
      case "save":
      case "done":
      case "delay":
        return "";
      default:
        return null;
    }
  }

  // ---- fields --------------------------------------------------------------
  const KIND = (fact) => {
    if (fact === "resume") return "file";
    if (fact === "step") return "step";
    if (/^(education|experience)$/.test(fact || "")) return "group";
    if (/^(work_authorized|needs_sponsorship|yes|no|consent)$/.test(fact || "")) return "yesno";
    if (/^(gender|ethnicity|hispanic|veteran|disability|referral_source|country|state|degree|phone_type|phone_country)$/.test(fact || "")) return "select";
    return "text";
  };
  const isGroup = (v) => !!(v.group || v.array || v.inputSelectors);
  const isManual = (spec) => spec.variants.length > 0 && spec.variants.every((v) => v.manual);
  const plainPaths = (spec) => spec.variants.filter((v) => !isGroup(v)).flatMap((v) => v.paths || []);
  const submitEl = () => first(cfg.submit || [], {}, document, true)?.el || null;

  function groupPresent(spec, root) {
    return spec.variants.some((v) => isGroup(v) && (first(v.addButtonPath || [], {}, root) || first(v.containerPath || [], { index: 0 }, root) || countEntries(v) > 0));
  }
  // How many entries a group shows: its containers under any number the
  // page gave them, or the rows its confirm path names.
  function countEntries(v) {
    const found = new Set();
    for (const path of list(v.containerPath)) for (let n = 0; n < 30; n++) for (const el of $x(expand(path, { index: n }))) found.add(el);
    for (const path of list(v.confirmAddedPath)) for (let n = 0; n < 30; n++) for (const el of $x(expand(path, { index: n }))) found.add(el);
    return found.size;
  }
  // Steps are the table's flow: open the form, expand a section, save it.
  // They run in table order around the fields they sit between, are never
  // read to the panel and never asked of the model, and a step whose path
  // is not on the page is skipped.
  const ranSteps = new Set();
  async function runStep(spec, root) {
    ranSteps.add(spec.name);
    for (const v of spec.variants) {
      if (isGroup(v) || v.manual) continue;
      const found = first(v.paths, { value: "" }, root, v.hidden === true);
      if (!found || found.el === submitEl()) continue;
      await runMethod(v.method, found.el, "", null, v.eventOptions);
      await runActions(v.actions, { inputPath: found.path, value: "" }, root, found.el, "", null);
      return true;
    }
    return false;
  }
  async function stepsBefore(index, root) {
    for (let i = 0; i < index; i++) {
      const f = cfg.fields[i];
      if (KIND(f.fact) === "step" && !ranSteps.has(f.name)) await runStep(f, root);
    }
  }
  const lastFieldIndex = () => {
    let last = -1;
    cfg.fields.forEach((f, i) => {
      if (KIND(f.fact) !== "step") last = i;
    });
    return last;
  };

  function factFields(root) {
    const out = [];
    cfg.fields.forEach((f, i) => {
      const kind = KIND(f.fact);
      if (kind === "step") return;
      const base = { key: `fact:${f.name}`, label: f.name.replace(/_/g, " "), kind, required: false, options: [], fact: f.fact, _spec: f, _index: i, _person: isManual(f) };
      if (kind === "group") {
        if (groupPresent(f, root)) out.push({ ...base, _el: null });
        return;
      }
      const probe = first(plainPaths(f), { value: "" }, root, f.variants.some((v) => v.hidden === true));
      if (probe) out.push({ ...base, _el: probe.el });
    });
    return out;
  }
  // The containers the repeated groups on this page own (work experience 1,
  // 2, ...; education 1, ...): the inputs inside them are the group's, not
  // questions. Read as questions they took the block's heading as their
  // label and the resolve answered "Job Title" into company, dates and
  // description alike (Workday, report 8).
  function groupContainers(root) {
    const out = [];
    for (const f of cfg.fields) {
      for (const v of f.variants) {
        if (!isGroup(v)) continue;
        for (const path of list(v.containerPath)) {
          for (let n = 0; n < 15; n++) out.push(...$x(expand(path, { index: n, length: 15 }), root));
        }
      }
    }
    return out;
  }
  // A section's name: the element its aria-labelledby points at, a heading
  // itself, or the first heading inside it; never its whole text.
  function sectionName(el) {
    if (!el) return "";
    const ids = (el.getAttribute && el.getAttribute("aria-labelledby")) || "";
    for (const id of ids.split(/\s+/).filter(Boolean)) {
      const t = clean(text(document.getElementById(id)));
      if (t) return t.slice(0, 80);
    }
    if (/^H[1-6]$/.test(el.tagName)) return clean(text(el)).slice(0, 80);
    const h = el.querySelector && el.querySelector("h1, h2, h3, h4, h5, h6, legend");
    return h ? clean(text(h)).slice(0, 80) : "";
  }
  function questionFields(taken, root) {
    const out = [];
    const owned = groupContainers(root);
    for (const q of cfg.questions || []) {
      for (const box of list(q.fieldPath).flatMap((p) => $x(p, root))) {
        if (!visible(box)) continue;
        if (owned.some((c) => c !== box && c.contains(box))) continue;
        const input = list(q.inputPath).map((p) => $x(p, box)[0]).find(Boolean);
        const optionEls = list(q.optionsPath).flatMap((p) => $x(p, box));
        if (!input && !optionEls.length) continue;
        const anchor = input || optionEls[0];
        // A control a named fact already owns is not a question as well.
        if (taken.has(anchor) || optionEls.some((o) => taken.has(o))) continue;
        taken.add(anchor);
        const optionText = (o) => clean(list(q.optionsTextPath).map((p) => text($x(p, o)[0])).find((t) => t && t.trim()) || text(o) || o.value);
        let options = optionEls.map(optionText).filter(Boolean);
        // The question's label is the first candidate that is not one of its
        // own options; a group's option labels share the label selector.
        let label = clean(
          list(q.labelPath)
            .flatMap((p) => $x(p, box).map(text))
            .map(clean)
            .find((t) => t && !options.includes(t)),
        );
        if (!label) continue;
        // The section the question sits under names it too ("Education:
        // Degree" is not "Degree" on its own).
        const section = list(q.sectionPath).map((p) => sectionName($x(p, box)[0])).find((t) => t);
        if (section && !label.toLowerCase().startsWith(section.toLowerCase())) label = `${section}: ${label}`;
        let kind = "text";
        if (input && input.tagName === "TEXTAREA") kind = "long";
        else if (input && input.type === "file") kind = "file";
        else if (input && input.tagName === "SELECT") {
          kind = "select";
          options = [...input.options].map((o) => o.text.trim()).filter(Boolean);
        } else if (optionEls.length) kind = optionEls[0].type === "checkbox" ? "multiselect" : "select";
        else if (input && (input.getAttribute("role") === "combobox" || q.optionsSource)) kind = "select";
        out.push({
          key: (input && (input.name || input.id)) || (optionEls[0] && optionEls[0].name) || `label:${label}`,
          label,
          kind,
          required: /[*✱]\s*$/.test(clean(box.innerText)),
          options,
          _q: q,
          _box: box,
          _el: input || null,
          _options: optionEls.map((el, i) => ({ el, text: options[i] || "" })),
          _selectedPath: q.optionsSelectedPath || null,
          _textPath: q.inputTextPath || null,
          _fillEmpty: q.valueRequired === false,
        });
      }
    }
    return out;
  }
  // A form behind an Apply button (or an "apply manually" choice): the
  // button is clicked and the fields waited for. Never a submit.
  async function openForm() {
    for (const paths of [cfg.applyOptionPaths, cfg.applyButtonPaths]) {
      const btn = first(paths || [], {}, document, false);
      if (!btn || btn.el === submitEl()) continue;
      clickOn(btn.el, { noBlur: true });
      const deadline = Date.now() + 8000;
      while (Date.now() < deadline && !anyField()) await sleep(200);
    }
  }
  const excluded = () => anyGroup(cfg.pathsExcluded);
  const domOrder = (a, b) => {
    const x = a._el || a._box;
    const y = b._el || b._box;
    if (!x || !y || x === y) return 0;
    return x.compareDocumentPosition(y) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1;
  };
  async function read() {
    ranSteps.clear();
    if (excluded()) return [];
    if (!anyField()) await openForm();
    const root = scope();
    if (!root) return [];
    const facts = factFields(root);
    const out = [...facts, ...questionFields(new Set(facts.map((f) => f._el).filter(Boolean)), root)];
    return cfg.orderByDomPosition === false ? out : out.sort(domOrder);
  }

  const optionLabel = (i) => clean(i.closest("label")?.innerText || document.querySelector(`label[for="${CSS.escape(i.id)}"]`)?.innerText || i.value);
  function current(field) {
    if (field.kind === "group") {
      const n = field._spec.variants
        .filter(isGroup)
        .reduce((acc, v) => acc + countEntries(v), 0);
      return n ? `${n} entries` : "";
    }
    if (field._options && field._options.length) {
      const selected = (o) =>
        field._selectedPath
          ? list(field._selectedPath).some((p) => $x(p, o.el).length)
          : o.el.checked || o.el.getAttribute("aria-selected") === "true" || o.el.getAttribute("aria-checked") === "true";
      const on = field._options.filter(selected);
      if (on.length || !field._el) return on.map((o) => o.text).join(" | ");
    }
    // A custom widget shows its value somewhere other than an input.
    if (field._textPath && field._box) {
      const t = list(field._textPath).map((p) => text($x(p, field._box)[0])).find((s) => s && s.trim());
      if (t) return clean(t);
    }
    const el = field._el;
    if (!el || !el.isConnected) return "";
    if (el.type === "file") return el.files && el.files.length ? el.files[0].name : "";
    if (el.tagName === "SELECT") return el.selectedOptions[0]?.text.trim() || "";
    if (el.type === "radio" || el.type === "checkbox") {
      const group = el.name ? [...document.querySelectorAll(`input[name="${CSS.escape(el.name)}"]`)] : [el];
      return group.filter((i) => i.checked).map(optionLabel).join(" | ");
    }
    return el.value || "";
  }

  async function fillVariants(variants, value, file, root, ctx) {
    const wants = String(value ?? "").split("|").map((s) => s.trim()).filter(Boolean);
    for (const want of wants.length ? wants : [""]) {
      for (const v of variants) {
        if (isGroup(v) || v.manual) continue;
        for (const candidate of candidates(v, ctx, want)) {
          // A path per value, or the one path with the value in it.
          const paths = v.valuePathMap ? mapPath(v.valuePathMap, candidate) : v.paths;
          if (!paths) continue;
          const vctx = { ...ctx, value: candidate, raw: want };
          const found = await waitFirst(paths, vctx, root, v.hidden === true, v.time || 0);
          if (!found) {
            note(`variant ${variants.indexOf(v)}: anchor not on page for "${candidate}"`);
            continue;
          }
          let ok;
          try {
          if (v.valuePath) {
            const opt = await waitFirst(v.valuePath, { ...vctx, inputPath: found.path }, root, true, v.valueElementTime || 300);
            ok = opt ? pickOption(opt.el) : false;
          } else if (!v.method && v.actions && v.actions.length) {
            // A variant with actions and no method of its own: the anchor is
            // only the %INPUTPATH% the actions refer to, and the actions do
            // all the work. Clicking it first opened Workday's dropdown so
            // the recipe's own click closed it again (2026-09-08).
            ok = true;
          } else {
            ok = await runMethod(v.method, found.el, candidate, file, v.eventOptions);
          }
          const acted = await runActions(v.actions, { ...vctx, inputPath: found.path }, root, found.el, candidate, file);
          if (ok && acted) {
            note(`variant ${variants.indexOf(v)}: took "${candidate}"`);
            return true;
          }
          note(`variant ${variants.indexOf(v)}: ${ok ? "actions failed" : "method failed"} for "${candidate}"`);
          } catch (e) {
            // One variant's error is that variant's; the next may work, and
            // the trace says what happened.
            note(`variant ${variants.indexOf(v)}: ${String(e)}`);
          }
        }
      }
    }
    return false;
  }

  // One entry per profile row: add a container when the page has fewer than
  // the row needs, then every nested field the row has a value for.
  async function fillGroup(group, items, file, fact, asName = null, parentRoot = null, entryNumber = null) {
    const rows = group.limit ? items.slice(0, group.limit) : items;
    const ordered = group.reverse ? [...rows].reverse() : rows;
    let filledAny = false;
    for (let i = 0; i < ordered.length; i++) {
      const item = ordered[i];
      const ctx = { index: i, length: ordered.length, item, fact };
      if (i && cfg.fillInputGroupInterval) await sleep(cfg.fillInputGroupInterval);
      // The entry containers on the page, in page order, whichever number
      // the page gave each: the table's path counts 1, 2, 3 in %NUMBER0%,
      // but Workday numbers a block from a running counter (a fresh block
      // was workExperience-6, report 8), so every number up to thirty is
      // tried and the i-th container found is the i-th entry.
      const containerPaths = list(group.containerPath);
      // Each container remembers the number it was found under: a recipe
      // inside the entry may name the entry by number too (Workday's
      // field-of-study click names education-%NUMBER0%), and the page's own
      // number is the one that matches, not the entry's position.
      const numberOf = new Map();
      const allContainers = () => {
        for (const path of containerPaths) {
          for (let n = 0; n < 30; n++) for (const el of $x(expand(path, { ...ctx, index: n }))) if (!numberOf.has(el)) numberOf.set(el, n);
        }
        return [...numberOf.keys()].sort((a, b) => (a.compareDocumentPosition(b) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1));
      };
      // A nested group of one widget (company inside an experience, school
      // inside an education) has no container of its own: it fills inside
      // its parent's entry (report 12: company, school and field of study
      // never ran because it had none).
      let containers = containerPaths.length ? allContainers() : parentRoot ? [parentRoot] : [];
      if (containerPaths.length && containers.length <= i) {
        const add = first(group.addButtonPath || [], ctx);
        if (!add) {
          note(`${fact} entry ${i + 1}: no add button`);
          break;
        }
        clickOn(add.el, { noBlur: true });
        const deadline = Date.now() + (group.time || 4000);
        while (Date.now() < deadline) {
          containers = allContainers();
          if (containers.length > i) break;
          await sleep(150);
        }
        if (containers.length <= i) note(`${fact} entry ${i + 1}: add clicked, no container appeared`);
      }
      // Inside the entry's container or not at all: against the document
      // the same selector matches the form's own fields (Workable's
      // Summary box).
      // The i-th container or nothing: falling back to the last one wrote
      // the second education into the first block (capture 25).
      const root = containers[i];
      if (!root) {
        note(`${fact} entry ${i + 1}: no container for it, stopping`);
        break;
      }
      const pageNumber = entryNumber ?? numberOf.get(root) ?? i;
      const entryCtx = { ...ctx, index: pageNumber };
      note(`${fact} entry ${i + 1}: filling${pageNumber !== i ? ` (page number ${pageNumber + 1})` : ""}`);
      for (const nested of group.fields || []) {
        // A nested group of one field ("major" holding "name") takes the
        // outer name's value: the inner "name" is the widget, not the fact.
        const value = entryValue(asName || nested.name, item, fact);
        if (value === null) continue;
        for (const v of nested.variants) {
          if (isGroup(v)) await fillGroup({ ...v, containerPath: v.containerPath || [] }, [item], file, fact, asName || nested.name, root, pageNumber);
        }
        const plain = nested.variants.filter((v) => !isGroup(v));
        if (plain.length) {
          try {
            // A widget that takes several values (Workday's field of study
            // is a multi-select: two majors, two picks) takes every
            // alternative; any other takes the first that lands.
            const multi = plain.some((v) => list(v.paths).some((p) => /multiselect/i.test(p)));
            const parts = multi ? String(value).split("|").map((x) => x.trim()).filter(Boolean) : [String(value)];
            let took = false;
            for (const part of parts) took = (await fillVariants(plain, part, file, root, entryCtx)) || took;
            note(`${nested.name} = "${String(value).slice(0, 40)}": ${took ? "took" : "not taken"}${multi ? ` (${parts.length} picks)` : ""}`);
          } catch (e) {
            note(`${nested.name}: ${String(e)}`);
          }
        }
        if (cfg.fillInputInterval) await sleep(cfg.fillInputInterval);
      }
      filledAny = true;
      if (list(group.confirmAddedPath).length) {
        const deadline = Date.now() + 3000;
        while (Date.now() < deadline && !first(group.confirmAddedPath, ctx)) await sleep(150);
      }
    }
    return filledAny;
  }

  async function fill(field, value, file) {
    const root = scope() || document;
    trace = field._trace = [];
    seenOptions = null;
    try {
      return await fillInner(field, value, file, root);
    } finally {
      // The options a search showed and nothing matched: the panel's model
      // call gets them and its pick comes back through fill as an exact.
      if (seenOptions && seenOptions.length) field._seen = seenOptions;
    }
  }
  async function fillInner(field, value, file, root) {
    if (field._spec) {
      // The flow steps the table puts before this field, then the field,
      // then the steps that close the form when this is its last field.
      await stepsBefore(field._index, root);
      let ok = false;
      if (field._person) ok = false;
      else if (field.kind === "group") {
        const items = ((window.__jtProfile || {})[field.fact] || []).filter((x) => x && (x.company || x.school));
        if (items.length) for (const v of field._spec.variants) if (isGroup(v)) ok = (await fillGroup(v, items, file, field.fact)) || ok;
      } else {
        // A date the field names a format for: today's date is ours to
        // supply, a birthday must come with the value.
        let v = value;
        if (field.fact === "today") v = formatDate(field._spec.name, parseDate(value) || todayParts());
        else if (field.fact === "birthday") v = formatDate(field._spec.name, parseDate(value));
        // A file field carries the file, not a value; its recipe runs with
        // the file (report 12: the resume never ran on a null value).
        if (field.kind === "file") ok = file ? await fillVariants(field._spec.variants, "", file, root, {}) : false;
        else ok = v == null ? false : await fillVariants(field._spec.variants, v, file, root, {});
      }
      if (field._index === lastFieldIndex()) await stepsBefore(cfg.fields.length, root);
      if (cfg.fillInputInterval) await sleep(cfg.fillInputInterval);
      return ok;
    }
    const wants = String(value ?? "").split("|").map((s) => s.trim()).filter(Boolean);
    if (field._q && field._q.fillActions && (field._options?.length || field._fillEmpty) && !field._el?.tagName?.match(/SELECT|TEXTAREA/)) {
      // A custom choice with its own recipe: open the list, click the option.
      // A recipe that needs no value (a "today" button) runs once with none.
      for (const want of wants.length ? wants : field._fillEmpty ? [""] : []) {
        if (await runActions(field._q.fillActions, { value: want }, field._box, field._el, want, file)) {
          await sleep(200);
          if (current(field) || field._fillEmpty) return true;
        }
      }
    }
    if (field._options && field._options.length && field._options[0].el.type) {
      let took = false;
      for (const o of field._options) {
        if (wants.map((w) => w.toLowerCase()).includes(o.text.toLowerCase()) && !o.el.checked) {
          checkOrRadio(o.el, true);
          took = true;
          if (o.el.type === "radio") break;
        }
      }
      if (took) return true;
    }
    const el = field._el;
    if (!el || !el.isConnected) return false;
    let ok;
    if (field.kind === "file") ok = uploadFile(el, file);
    else if (el.tagName === "SELECT") ok = chooseNative(el, value);
    else if (el.type === "radio" || el.type === "checkbox") ok = checkOrRadio(el, true);
    else ok = typeInto(el, wants[0] ?? "", null, cfg.defaultMethod === "default");
    if (cfg.fillInputInterval) await sleep(cfg.fillInputInterval);
    return ok;
  }

  const nextButton = () => first(cfg.continue || [])?.el || null;
  const submitButton = () => first(cfg.submit || [])?.el || null;
  // A modal the ATS raises after submit (a chatbot with more questions)
  // means the application is not in yet.
  const submitted = () => !first(cfg.deferSubmissionModalPaths || []) && (cfg.success || []).some((p) => $x(p).length > 0);
  // The fields the page marks invalid, within the scope the table names.
  const errors = () => {
    const roots = list(cfg.validationScopePaths).flatMap((p) => $x(p));
    const within = roots.length ? roots : [document];
    return within
      .flatMap((r) => [...r.querySelectorAll('[aria-invalid="true"], .error input, .has-error input')])
      .map((el) => clean(el.labels?.[0]?.innerText || el.getAttribute("aria-label") || el.name || el.id));
  };
  const anyField = () => {
    const root = scope();
    if (!root) return false;
    return (
      !!first(cfg.fields.filter((f) => KIND(f.fact) !== "step").flatMap(plainPaths), { value: "" }, root) ||
      cfg.fields.some((f) => KIND(f.fact) === "group" && groupPresent(f, root)) ||
      (cfg.questions || []).some((q) => list(q.fieldPath).some((p) => $x(p, root).some(visible)))
    );
  };
  const applyButton = () => !!first(cfg.applyButtonPaths || [], {}, document, false) || !!first(cfg.applyOptionPaths || [], {}, document, false);
  const ready = () => !excluded() && (anyField() || applyButton());

  window.__jtReader = {
    host: cfg.name.toLowerCase(),
    ready,
    read,
    fill,
    current,
    submitButton,
    nextButton,
    submitted,
    errors,
    proxySubmit: !!cfg.proxySubmit,
  };
})();
