// The config-driven reader. extension/ats/<ATS>.js (generated by
// tools/convert_ats_config.py) describes one ATS as data: url match
// patterns, fields that name the fact they take and the selectors and fill
// method that take it, repeated groups (education, experience) with an add
// button and nested fields, the selectors that find custom questions and
// how to answer them, and the continue, submit and success paths. This file
// interprets that data for the matching ATS and exposes the same reader
// interface the hand-written readers do, plus a step model for forms that
// span pages.
(() => {
  if (window.__jtReader) return; // a hand-written reader owns this host
  const configs = window.__jtATS || [];
  const matchesPattern = (pattern, url) => {
    const re = new RegExp(
      "^" + pattern.split("*").map((s) => s.replace(/[.+?^${}()|[\]\\]/g, "\\$&")).join(".*") + "$",
    );
    return re.test(url);
  };
  const cfg = configs.find((c) => c.matches.some((m) => matchesPattern(m, location.href)));
  if (!cfg) return;

  const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
  const clean = (s) => (s || "").replace(/\s+/g, " ").replace(/[*✱]\s*$/, "").trim();
  const list = (x) => (Array.isArray(x) ? x : x ? [x] : []);

  // XPath with the table's placeholders: %INPUTPATH% is the field's own
  // path, %VALUE% and its cases the value being filled, %NUMBER0% and
  // %INDEX0% the entry of a repeated group, one- and zero-based.
  function expand(path, ctx) {
    const v = ctx.value || "";
    return path
      .replaceAll("%INPUTPATH%", ctx.inputPath || "")
      .replaceAll("%UPPERUNMAPPEDVALUE%", (ctx.raw || v).toUpperCase())
      .replaceAll("%LOWERUNMAPPEDVALUE%", (ctx.raw || v).toLowerCase())
      .replaceAll("%UNMAPPEDVALUE%", ctx.raw || v)
      .replaceAll("%UPPERVALUE%", v.toUpperCase())
      .replaceAll("%LOWERVALUE%", v.toLowerCase())
      .replaceAll("%VALUE%", v)
      .replaceAll("%NUMBER0%", String((ctx.index ?? 0) + 1))
      .replaceAll("%INDEX0%", String(ctx.index ?? 0))
      .replaceAll("%LENGTHPLUSONE0%", String((ctx.length ?? 0) + 1));
  }
  function $x(path, root = document) {
    const out = [];
    try {
      const it = document.evaluate(path, root, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
      for (let i = 0; i < it.snapshotLength; i++) out.push(it.snapshotItem(i));
    } catch (_) {
      // A selector the page's XPath engine rejects is a selector that
      // matches nothing.
    }
    return out;
  }
  const text = (node) => (node && node.nodeType === Node.TEXT_NODE ? node.textContent : node ? node.innerText || node.textContent : "");
  const visible = (el) => !!el && (el.nodeType !== Node.ELEMENT_NODE || el.offsetParent !== null || el.getClientRects().length > 0 || el.type === "file" || el.type === "hidden");
  function first(paths, ctx = {}, root = document) {
    for (const p of list(paths)) {
      const hit = $x(expand(p, ctx), root).find(visible);
      if (hit) return { el: hit, path: expand(p, ctx) };
    }
    return null;
  }

  // ---- fill methods, one per name the table uses ---------------------------
  const events = (extra) => ({ bubbles: true, cancelable: true, ...(cfg.defaultEventOptions || {}), ...(extra || {}) });
  function setValue(el, value) {
    const proto = el.tagName === "TEXTAREA" ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype;
    const setter = Object.getOwnPropertyDescriptor(proto, "value")?.set;
    if (setter) setter.call(el, value);
    else el.value = value;
    el.setAttribute("value", value);
  }
  function typeInto(el, value, opts, blur) {
    const t = events(opts);
    el.dispatchEvent(new FocusEvent("focus", t));
    setValue(el, value);
    el.dispatchEvent(new CustomEvent("textInput", t));
    el.dispatchEvent(new InputEvent("input", t));
    el.dispatchEvent(new Event("change", t));
    if (blur) el.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  function clickOn(el, opts) {
    const t = events(opts);
    el.dispatchEvent(new FocusEvent("focus", t));
    el.dispatchEvent(new MouseEvent("mousedown", t));
    el.dispatchEvent(new MouseEvent("mouseup", t));
    if (typeof el.click === "function") el.click();
    else el.dispatchEvent(new MouseEvent("click", t));
    if (!(opts && opts.noBlur)) el.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  function chooseNative(el, value) {
    const wants = String(value).split("|").map((s) => s.trim().toLowerCase()).filter(Boolean);
    const opts = [...el.options];
    const opt =
      opts.find((o) => wants.includes(o.text.trim().toLowerCase()) || wants.includes(o.value.toLowerCase())) ||
      opts.find((o) => wants.some((w) => o.text.trim().toLowerCase().startsWith(w)));
    if (!opt) return false;
    const t = events();
    el.dispatchEvent(new FocusEvent("focus", t));
    el.value = opt.value;
    el.dispatchEvent(new InputEvent("input", t));
    el.dispatchEvent(new Event("change", t));
    el.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  function checkOrRadio(el, on) {
    const t = events();
    if (Boolean(el.checked) === Boolean(on)) return true;
    el.dispatchEvent(new FocusEvent("focus", t));
    if (el.type === "checkbox") el.click();
    else {
      el.dispatchEvent(new MouseEvent("click", t));
      el.checked = Boolean(on);
    }
    el.dispatchEvent(new InputEvent("input", t));
    el.dispatchEvent(new Event("change", t));
    el.dispatchEvent(new FocusEvent("blur", t));
    return true;
  }
  function uploadFile(el, file) {
    if (!file) return false;
    const dt = new DataTransfer();
    dt.items.add(file);
    el.files = dt.files;
    el.dispatchEvent(new Event("change", events()));
    return true;
  }
  async function runMethod(method, el, value, file, opts) {
    const m = method || cfg.defaultMethod || "default";
    switch (m) {
      case "uploadResume":
        return uploadFile(el, file);
      case "click":
      case "reactClick":
        return clickOn(el, opts);
      case "selectCheckboxOrRadio":
        return checkOrRadio(el, true);
      case "clearValue":
        return typeInto(el, "", opts, false);
      case "blur":
        el.dispatchEvent(new FocusEvent("blur", events(opts)));
        return true;
      case "scrollListboxToOption":
        el.scrollIntoView({ block: "center" });
        return clickOn(el, { ...opts, noBlur: true });
      case "reactDatePickerMonth": {
        // A month picker fed by typing: the value, then Enter, then away.
        typeInto(el, value, opts, false);
        el.dispatchEvent(new KeyboardEvent("keydown", { key: "Enter", code: "Enter", keyCode: 13, bubbles: true }));
        await sleep(150);
        el.dispatchEvent(new FocusEvent("blur", events(opts)));
        return true;
      }
      default: {
        const blur = m === "default";
        if (el.tagName === "SELECT") return chooseNative(el, value);
        if (el.type === "checkbox" || el.type === "radio") return checkOrRadio(el, true);
        if (el.tagName === "INPUT" || el.tagName === "TEXTAREA") return typeInto(el, value, opts, blur);
        return clickOn(el, opts);
      }
    }
  }

  // The table's action list: each step waits up to `time` for its path,
  // skips itself on a failed `condition`, and either fires an event, waits
  // for its path to be removed, or runs a method on what it found.
  async function runActions(actions, ctx, root, fallbackEl, value, file) {
    for (const a of actions || []) {
      if (a.delay) await sleep(a.delay);
      if (a.condition && !$x(expand(a.condition, ctx), root).length) continue;
      if (a.valueRequired && !value) continue;
      if (a.removed) {
        const deadline = Date.now() + (a.time || 1000);
        while (Date.now() < deadline && first(a.path || ["."], ctx, root)) await sleep(100);
        continue;
      }
      let target = a.path ? null : { el: fallbackEl, path: ctx.inputPath };
      const deadline = Date.now() + (a.time || 0);
      while (!target) {
        target = first(a.path, ctx, root);
        if (target || Date.now() >= deadline) break;
        await sleep(150);
      }
      if (!target) {
        if (a.allowFailure) continue;
        return false;
      }
      if (a.event) target.el.dispatchEvent(new Event(a.event, events(a.eventOptions)));
      else await runMethod(a.method || "click", target.el, value, file, a.eventOptions);
    }
    return true;
  }

  // A `values` map in the table names answers by code and lists the option
  // texts each code may appear as; our text picks the code whose texts it
  // matches, and those texts are tried in turn.
  function mapValues(values, ours) {
    if (!values || typeof values !== "object" || !ours) return [ours];
    const low = ours.toLowerCase();
    for (const texts of Object.values(values)) {
      const options = list(texts).map(String);
      if (options.some((t) => t.toLowerCase() === low || low.startsWith(t.toLowerCase()) || t.toLowerCase().startsWith(low))) {
        return [...new Set([ours, ...options])];
      }
    }
    return [ours];
  }

  // ---- dates and entry values for repeated groups --------------------------
  const MONTHS = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
  function parseDate(s) {
    if (!s) return null;
    const t = String(s).trim();
    let m = t.match(/^(\d{4})-(\d{1,2})(?:-(\d{1,2}))?$/);
    if (m) return { y: +m[1], m: +m[2], d: +(m[3] || 1) };
    m = t.match(/^(\d{1,2})\/(?:(\d{1,2})\/)?(\d{4})$/);
    if (m) return { y: +m[3], m: +m[1], d: +(m[2] || 1) };
    m = t.match(/^([A-Za-z]{3,9})\.?\s+(\d{4})$/);
    if (m) {
      const idx = MONTHS.findIndex((n) => n.toLowerCase().startsWith(m[1].slice(0, 3).toLowerCase()));
      if (idx >= 0) return { y: +m[2], m: idx + 1, d: 1 };
    }
    m = t.match(/^(\d{4})$/);
    if (m) return { y: +m[1], m: 1, d: 1 };
    return null;
  }
  const pad = (n) => String(n).padStart(2, "0");
  function formatDate(name, d) {
    if (!d) return null;
    if (/month_text/.test(name)) return MONTHS[d.m - 1];
    if (/month_abbr/.test(name)) return MONTHS[d.m - 1].slice(0, 3);
    if (/_month$/.test(name)) return `${d.m} | ${pad(d.m)} | ${MONTHS[d.m - 1]}`;
    if (/_year$/.test(name)) return String(d.y);
    if (/_(day|D)$/.test(name)) return String(d.d);
    if (/slashes_MMDDYYYY|_MMDDYYYY$/.test(name)) return `${pad(d.m)}/${pad(d.d)}/${d.y}`;
    if (/slashes_MDYYYY/.test(name)) return `${d.m}/${d.d}/${d.y}`;
    if (/slashes_MMYYYY|_MMYYYY$/.test(name)) return `${pad(d.m)}/${d.y}`;
    if (/dashes_YYYYMMDD/.test(name)) return `${d.y}-${pad(d.m)}-${pad(d.d)}`;
    if (/dashes_YYYYMM/.test(name)) return `${d.y}-${pad(d.m)}`;
    if (/dashes_MMMYYYY/.test(name)) return `${MONTHS[d.m - 1].slice(0, 3)}-${d.y}`;
    if (/dashes_MMYYYY/.test(name)) return `${pad(d.m)}-${d.y}`;
    if (/month_DD_comma_YYYY/.test(name)) return `${MONTHS[d.m - 1]} ${pad(d.d)}, ${d.y}`;
    if (/_MM$/.test(name)) return pad(d.m);
    return `${pad(d.m)}/${d.y}`;
  }
  // What a nested field takes from one profile row, by the table's name for
  // it. null means the field is not ours to fill for this row.
  function entryValue(name, item, fact) {
    const start = parseDate(item.start);
    const end = parseDate(item.end);
    const now = new Date();
    if (/^(start|begin)/.test(name)) return formatDate(name, start);
    if (/^(grad|end|actual_completion)/.test(name)) return item.current ? null : formatDate(name, end);
    switch (name) {
      case "education":
      case "school":
      case "name":
        return fact === "education" ? item.school : item.company;
      case "major":
      case "field":
        return item.field || null;
      case "degree":
        return item.degree || null;
      case "gpa":
        return item.gpa || null;
      case "graduated":
      case "did_graduate":
      case "qualification_complete":
        return end && new Date(end.y, end.m - 1, 1) <= now ? "Yes" : "No";
      case "title":
        return item.title || null;
      case "company":
      case "employer":
        return item.company || null;
      case "location":
      case "city_state":
      case "city_state_full":
        return item.location || null;
      case "city":
        return item.location ? item.location.split(",")[0].trim() : null;
      case "state":
        return item.location && item.location.includes(",") ? item.location.split(",")[1].trim() : null;
      case "country":
        return item.location && item.location.split(",").length > 2 ? item.location.split(",").pop().trim() : null;
      case "description":
        return item.description || null;
      case "description_stripped":
        return item.description ? item.description.replace(/\s+/g, " ").trim() : null;
      case "currently_working":
        return item.current ? "Yes" : null;
      case "save":
      case "done":
      case "delay":
        return "";
      default:
        return null;
    }
  }

  // ---- fields --------------------------------------------------------------
  const KIND = (fact) =>
    fact === "resume" ? "file" : /^(education|experience)$/.test(fact || "") ? "group" : /^(work_authorized|needs_sponsorship|yes|consent)$/.test(fact || "") ? "yesno" : /^(gender|ethnicity|hispanic|veteran|disability|referral_source|country|state|degree)$/.test(fact || "") ? "select" : "text";

  function groupPresent(spec) {
    return spec.variants.some((v) => v.group && (first(v.addButtonPath || [], {}) || first(v.containerPath || [], {})));
  }
  function factFields() {
    const out = [];
    for (const f of cfg.fields) {
      const kind = KIND(f.fact);
      if (kind === "group") {
        if (!groupPresent(f)) continue;
        out.push({ key: `fact:${f.name}`, label: f.name.replace(/_/g, " "), kind, required: false, options: [], fact: f.fact, _spec: f, _el: null });
        continue;
      }
      const probe = first(f.variants.filter((v) => !v.group).flatMap((v) => v.paths || []), { value: "" });
      if (!probe) continue;
      out.push({ key: `fact:${f.name}`, label: f.name.replace(/_/g, " "), kind, required: false, options: [], fact: f.fact, _spec: f, _el: probe.el });
    }
    return out;
  }
  function questionFields(taken) {
    const out = [];
    for (const q of cfg.questions || []) {
      for (const box of list(q.fieldPath).flatMap((p) => $x(p))) {
        if (!visible(box)) continue;
        const input = list(q.inputPath).map((p) => $x(p, box)[0]).find(Boolean);
        const optionEls = list(q.optionsPath).flatMap((p) => $x(p, box));
        if (!input && !optionEls.length) continue;
        const anchor = input || optionEls[0];
        // A control a named fact already owns is not a question as well.
        if (taken.has(anchor) || optionEls.some((o) => taken.has(o))) continue;
        taken.add(anchor);
        const optionText = (o) => clean(list(q.optionsTextPath).map((p) => text($x(p, o)[0])).find((t) => t && t.trim()) || text(o) || o.value);
        let options = optionEls.map(optionText).filter(Boolean);
        // The question's label is the first candidate that is not one of its
        // own options; a group's option labels share the label selector.
        const label = clean(
          list(q.labelPath)
            .flatMap((p) => $x(p, box).map(text))
            .map(clean)
            .find((t) => t && !options.includes(t)),
        );
        if (!label) continue;
        let kind = "text";
        if (input && input.tagName === "TEXTAREA") kind = "long";
        else if (input && input.type === "file") kind = "file";
        else if (input && input.tagName === "SELECT") {
          kind = "select";
          options = [...input.options].map((o) => o.text.trim()).filter(Boolean);
        } else if (optionEls.length) kind = optionEls[0].type === "checkbox" ? "multiselect" : "select";
        else if (input && input.getAttribute("role") === "combobox") kind = "select";
        out.push({
          key: (input && (input.name || input.id)) || (optionEls[0] && optionEls[0].name) || `label:${label}`,
          label,
          kind,
          required: /[*✱]\s*$/.test(clean(box.innerText)),
          options,
          _q: q,
          _box: box,
          _el: input || null,
          _options: optionEls.map((el, i) => ({ el, text: options[i] || "" })),
        });
      }
    }
    return out;
  }
  async function read() {
    const facts = factFields();
    return [...facts, ...questionFields(new Set(facts.map((f) => f._el).filter(Boolean)))];
  }

  const optionLabel = (i) => clean(i.closest("label")?.innerText || document.querySelector(`label[for="${CSS.escape(i.id)}"]`)?.innerText || i.value);
  function current(field) {
    if (field.kind === "group") {
      const n = field._spec.variants
        .filter((v) => v.group)
        .reduce((acc, v) => acc + (list(v.containerPath).length ? $x(list(v.containerPath)[0]).length : 0) + (list(v.confirmAddedPath).length ? $x(expand(list(v.confirmAddedPath)[0], { index: 0 })).length : 0), 0);
      return n ? `${n} entries` : "";
    }
    if (field._options && field._options.length) {
      const on = field._options.filter((o) => o.el.checked || o.el.getAttribute("aria-selected") === "true");
      if (on.length || !field._el) return on.map((o) => o.text).join(" | ");
    }
    const el = field._el;
    if (!el || !el.isConnected) return "";
    if (el.type === "file") return el.files && el.files.length ? el.files[0].name : "";
    if (el.tagName === "SELECT") return el.selectedOptions[0]?.text.trim() || "";
    if (el.type === "radio" || el.type === "checkbox") {
      const group = el.name ? [...document.querySelectorAll(`input[name="${CSS.escape(el.name)}"]`)] : [el];
      return group.filter((i) => i.checked).map(optionLabel).join(" | ");
    }
    return el.value || "";
  }

  async function fillVariants(variants, value, file, root, ctx) {
    const wants = String(value ?? "").split("|").map((s) => s.trim()).filter(Boolean);
    for (const want of wants.length ? wants : [""]) {
      for (const v of variants) {
        if (v.group) continue;
        for (const candidate of mapValues(v.values, want)) {
          const found = first(v.paths, { ...ctx, value: candidate, raw: want }, root);
          if (!found) continue;
          const ok = await runMethod(v.method, found.el, candidate, file, v.eventOptions);
          const acted = await runActions(v.actions, { ...ctx, inputPath: found.path, value: candidate, raw: want }, root, found.el, candidate, file);
          if (ok && acted) return true;
        }
      }
    }
    return false;
  }

  // One entry per profile row: add a container when the page has fewer than
  // the row needs, then every nested field the row has a value for.
  async function fillGroup(group, items, file, fact, asName = null) {
    const rows = group.limit ? items.slice(0, group.limit) : items;
    const ordered = group.reverse ? [...rows].reverse() : rows;
    let filledAny = false;
    for (let i = 0; i < ordered.length; i++) {
      const item = ordered[i];
      const ctx = { index: i, length: ordered.length };
      const containerPath = list(group.containerPath)[0];
      let containers = containerPath ? $x(expand(containerPath, ctx)) : [];
      if (containerPath && containers.length <= i) {
        const add = first(group.addButtonPath || [], ctx);
        if (!add) break;
        clickOn(add.el, { noBlur: true });
        const deadline = Date.now() + (group.time || 4000);
        while (Date.now() < deadline) {
          containers = $x(expand(containerPath, ctx));
          if (containers.length > i) break;
          await sleep(150);
        }
      }
      // Inside the entry's container or not at all: against the document
      // the same selector matches the form's own fields (Workable's
      // Summary box).
      const root = containers[i] || containers[containers.length - 1];
      if (!root) break;
      for (const nested of group.fields) {
        // A nested group of one field ("major" holding "name") takes the
        // outer name's value: the inner "name" is the widget, not the fact.
        const value = entryValue(asName || nested.name, item, fact);
        if (value === null) continue;
        for (const v of nested.variants) {
          if (v.group) await fillGroup({ ...v, containerPath: v.containerPath || [] }, [item], file, fact, asName || nested.name);
        }
        const plain = nested.variants.filter((v) => !v.group);
        if (plain.length) await fillVariants(plain, value, file, root, ctx);
      }
      filledAny = true;
      if (list(group.confirmAddedPath).length) {
        const deadline = Date.now() + 3000;
        while (Date.now() < deadline && !first(group.confirmAddedPath, ctx)) await sleep(150);
      }
    }
    return filledAny;
  }

  async function fill(field, value, file) {
    if (field.kind === "group") {
      const items = ((window.__jtProfile || {})[field.fact] || []).filter((x) => x && (x.company || x.school));
      if (!items.length) return false;
      let ok = false;
      for (const v of field._spec.variants) if (v.group) ok = (await fillGroup(v, items, file, field.fact)) || ok;
      return ok;
    }
    if (field._spec) return fillVariants(field._spec.variants, value, file, document, {});
    const wants = String(value ?? "").split("|").map((s) => s.trim()).filter(Boolean);
    if (field._q && field._q.fillActions && field._options?.length && !field._el?.tagName?.match(/SELECT|TEXTAREA/)) {
      // A custom choice with its own recipe: open the list, click the option.
      for (const want of wants) {
        if (await runActions(field._q.fillActions, { value: want }, field._box, field._el, want, file)) {
          await sleep(200);
          if (current(field)) return true;
        }
      }
    }
    if (field._options && field._options.length && field._options[0].el.type) {
      let took = false;
      for (const o of field._options) {
        if (wants.map((w) => w.toLowerCase()).includes(o.text.toLowerCase()) && !o.el.checked) {
          checkOrRadio(o.el, true);
          took = true;
          if (o.el.type === "radio") break;
        }
      }
      if (took) return true;
    }
    const el = field._el;
    if (!el || !el.isConnected) return false;
    if (field.kind === "file") return uploadFile(el, file);
    if (el.tagName === "SELECT") return chooseNative(el, value);
    if (el.type === "radio" || el.type === "checkbox") return checkOrRadio(el, true);
    return typeInto(el, wants[0] ?? "", null, cfg.defaultMethod === "default");
  }

  const nextButton = () => first(cfg.continue || [])?.el || null;
  const submitButton = () => first(cfg.submit || [])?.el || null;
  const submitted = () => (cfg.success || []).some((p) => $x(p).length > 0);
  const anyField = () =>
    !!first(cfg.fields.flatMap((f) => f.variants.filter((v) => !v.group).flatMap((v) => v.paths || [])), { value: "" }) ||
    cfg.fields.some((f) => KIND(f.fact) === "group" && groupPresent(f)) ||
    (cfg.questions || []).some((q) => list(q.fieldPath).some((p) => $x(p).some(visible)));

  window.__jtReader = {
    host: cfg.name.toLowerCase(),
    ready: anyField,
    read,
    fill,
    current,
    submitButton,
    nextButton,
    submitted,
    proxySubmit: !!cfg.proxySubmit,
  };
})();
