"""Retain review gate decisions and outcomes

Revision ID: 01a2e66a5929
Revises: 81ad8119a446
Create Date: 2026-09-16 23:16:55.096212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '01a2e66a5929'
down_revision: Union[str, None] = '81ad8119a446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_gate_decisions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('filter_id', sa.BigInteger(), nullable=True),
    sa.Column('managed_board_id', sa.BigInteger(), nullable=True),
    sa.Column('revision', sa.BigInteger(), nullable=True),
    sa.Column('prompt_hash', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('skip','review')", name='ck_review_gate_decisions_action'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'url', name='uq_review_gate_decisions_task_url')
    )
    op.create_index('idx_review_gate_decisions_created', 'review_gate_decisions', ['created_at'], unique=False)
    op.create_index('idx_review_gate_decisions_url_created', 'review_gate_decisions', ['url', 'created_at'], unique=False)
    op.create_index('idx_review_gate_decisions_user_created', 'review_gate_decisions', ['user_id', 'created_at'], unique=False)
    op.create_table('review_gate_outcomes',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('decision_id', sa.BigInteger(), nullable=False),
    sa.Column('query_id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=False),
    sa.Column('recorded_cost_usd', sa.Numeric(), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', 'query_id', name='uq_review_gate_outcomes_decision_query')
    )
    op.create_index('idx_review_gate_outcomes_decision', 'review_gate_outcomes', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_review_gate_outcomes_decision', table_name='review_gate_outcomes')
    op.drop_table('review_gate_outcomes')
    op.drop_index('idx_review_gate_decisions_user_created', table_name='review_gate_decisions')
    op.drop_index('idx_review_gate_decisions_url_created', table_name='review_gate_decisions')
    op.drop_index('idx_review_gate_decisions_created', table_name='review_gate_decisions')
    op.drop_table('review_gate_decisions')
    # ### end Alembic commands ###
