"""Track compensation source provenance

Revision ID: 04648af4207c
Revises: ffd749f0cb15
Create Date: 2026-09-09 06:04:58.864840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "04648af4207c"
down_revision: Union[str, None] = "ffd749f0cb15"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("comp_content_row_id", sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "comp_content_row_id")
    # ### end Alembic commands ###
