"""source descriptions

Revision ID: 09f73ae6af6b
Revises: c79027fe8552
Create Date: 2026-08-24 00:11:06.513875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '09f73ae6af6b'
down_revision: Union[str, None] = 'c79027fe8552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('description', sa.Text(), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'description')
    # ### end Alembic commands ###
