"""Track application answer draft generations

Revision ID: 212d40885a0a
Revises: 7ac07584bcb5
Create Date: 2026-09-09 05:36:25.140647

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "212d40885a0a"
down_revision: Union[str, None] = "7ac07584bcb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application_answers",
        sa.Column("draft_revision", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application_answers", "draft_revision")
    # ### end Alembic commands ###
