"""progress_at

Revision ID: 2b80daf7ac80
Revises: a45f6ffe4306
Create Date: 2026-09-03 19:40:19.342066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2b80daf7ac80'
down_revision: Union[str, None] = 'a45f6ffe4306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('progress_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'progress_at')
    # ### end Alembic commands ###
