"""external request snapshot references

Revision ID: 343357c00e0e
Revises: d2c923541eaa
Create Date: 2026-10-03 03:28:19.617612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '343357c00e0e'
down_revision: Union[str, None] = 'd2c923541eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_requests', sa.Column('snapshot_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('batch_requests', 'snapshot_ref')
    # ### end Alembic commands ###
