"""drop batch_requests.snapshot and require snapshot_ref

Revision ID: 35d943a012cd
Revises: b223a0d76bc8
Create Date: 2026-10-10 04:08:48.374016

The contract half of the move of request snapshots to object storage. On
2026-10-10 production held 1,597,918 batch_requests rows, every one with a
version 3 bundle member reference and none with an inline snapshot. Writers
store only the reference, and since #901 no reader names `snapshot`; #901 ran
on every host (release 4bd90df2) before this was written. Every image that
names the column must be gone from the fleet before this applies, because a
dropped column fails every statement that names it.

Nothing here can drop data. ck_batch_requests_reference_only asserts that
`snapshot` is NULL and `snapshot_ref` is present. It is added NOT VALID (no
scan) and then validated, which scans the table (about 1.1 GB) under SHARE
UPDATE EXCLUSIVE: reads and writes continue. If any row holds an inline
snapshot or lacks a reference, VALIDATE raises, nothing is dropped, and the
container does not start. A rerun replaces the guard and validates again.

Then one short transaction: SET NOT NULL on snapshot_ref, which the validated
guard proves without a scan, drops the guard and drops the column. It holds
ACCESS EXCLUSIVE briefly and rewrites nothing. Dropping the column frees no
heap space, because NULLs occupy none.

Downgrade adds the column back empty and makes snapshot_ref nullable again.
That is what every release from #901 on needs; an older release read inline
snapshots, and none are left to read.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '35d943a012cd'
down_revision: Union[str, None] = 'b223a0d76bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLE = 'batch_requests'
_GUARD = 'ck_batch_requests_reference_only'


def upgrade() -> None:
    with op.get_context().autocommit_block():
        # bd1e66f153c3's judgment: a start can afford a minute for the
        # transactions in flight, and past that the wait is not ending.
        op.execute("SET lock_timeout = '60s'")
        op.execute(f"ALTER TABLE {_TABLE} DROP CONSTRAINT IF EXISTS {_GUARD}")
        op.execute(
            f"ALTER TABLE {_TABLE} ADD CONSTRAINT {_GUARD} "
            "CHECK (snapshot IS NULL AND snapshot_ref IS NOT NULL) NOT VALID"
        )
        op.execute(f"ALTER TABLE {_TABLE} VALIDATE CONSTRAINT {_GUARD}")
        op.execute("RESET lock_timeout")
    op.execute("SET LOCAL lock_timeout = '60s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(_TABLE, 'snapshot_ref',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_constraint(_GUARD, _TABLE, type_='check')
    op.drop_column(_TABLE, 'snapshot')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '60s'")
    # ### commands auto generated by Alembic - please adjust! ###
    # Adding a nullable column without a default rewrites nothing.
    op.add_column(_TABLE, sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column(_TABLE, 'snapshot_ref',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###
