"""task dedupe key

Revision ID: 366160ace55b
Revises: e41a9c2d7b10
Create Date: 2026-08-24 01:19:34.446277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '366160ace55b'
down_revision: Union[str, None] = 'e41a9c2d7b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('dedupe_key', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'tasks', ['dedupe_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'dedupe_key')
    # ### end Alembic commands ###
