"""add versioned job profiles

Revision ID: 39476e971cb3
Revises: 68622a4836a3
Create Date: 2026-09-11 20:45:23.262082

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "39476e971cb3"
down_revision: Union[str, None] = "68622a4836a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_profiles",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("content_row_id", sa.BigInteger(), nullable=False),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("classifier_version", sa.Text(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("primary_role_family", sa.Text(), nullable=False),
        sa.Column(
            "role_tracks",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("career_stage", sa.Text(), nullable=False),
        sa.Column("employment_type", sa.Text(), nullable=False),
        sa.Column("organization_sector", sa.Text(), nullable=False),
        sa.Column("people_manager", sa.Boolean(), nullable=True),
        sa.Column("company_selectivity", sa.Text(), nullable=False),
        sa.Column("role_selectivity", sa.Text(), nullable=False),
        sa.Column(
            "classified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("cardinality(role_tracks) <= 2", name="ck_job_profiles_two_tracks"),
        sa.ForeignKeyConstraint(["content_row_id"], ["ai_queries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "content_row_id", "classifier_version", "model", name="uq_job_profiles_derivation"
        ),
    )
    op.create_index(
        "idx_job_profiles_url_classified",
        "job_profiles",
        ["url", sa.literal_column("classified_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_job_profiles_url_classified", table_name="job_profiles")
    op.drop_table("job_profiles")
    # ### end Alembic commands ###
