"""record cache write token usage

Revision ID: 39622be0dedf
Revises: 6a9c2e1f4b70
Create Date: 2026-09-15 23:29:06.577500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '39622be0dedf'
down_revision: Union[str, None] = '6a9c2e1f4b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_batches', sa.Column('cache_write_tokens', sa.BigInteger(), nullable=True))
    op.add_column('ai_queries', sa.Column('cache_write_tokens', sa.BigInteger(), nullable=True))
    op.add_column('api_usage', sa.Column('cache_write_tokens', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_usage', 'cache_write_tokens')
    op.drop_column('ai_queries', 'cache_write_tokens')
    op.drop_column('ai_batches', 'cache_write_tokens')
    # ### end Alembic commands ###
