"""posting_uploads holds upload state

The expand step of moving a person's upload off the catalog row. A new empty
table, so it is additive. core.catalog writes it beside jobs.uploaded_by and
jobs.extraction_status from this release; tasks.posting_uploads copies the
uploads already there. Nothing reads it yet.

Revision ID: 3c9a33dbd847
Revises: 1276e94618f8
Create Date: 2026-10-10 14:14:35.853279

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "3c9a33dbd847"
down_revision: Union[str, None] = "1276e94618f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posting_uploads",
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column("uploaded_by", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'done', 'failed')", name="ck_posting_uploads_status"
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("job_id"),
    )
    op.create_index(
        "idx_posting_uploads_uploaded_by", "posting_uploads", ["uploaded_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_posting_uploads_uploaded_by", table_name="posting_uploads")
    op.drop_table("posting_uploads")
    # ### end Alembic commands ###
