"""enforce one saved view default per page

Revision ID: 5a736c33a9cf
Revises: e5f6a7b8c9d0
Create Date: 2026-09-09 03:41:01.527876

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "5a736c33a9cf"
down_revision: Union[str, None] = "e5f6a7b8c9d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Never choose between a person's saved defaults on their behalf. The
    # table lock keeps the preflight and index creation on the same population.
    op.execute("LOCK TABLE saved_views IN SHARE ROW EXCLUSIVE MODE")
    conflicts = (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT count(*) FROM (SELECT user_id, page FROM saved_views "
                "WHERE is_default GROUP BY user_id, page HAVING count(*) > 1) conflicts"
            )
        )
        .scalar_one()
    )
    if conflicts:
        raise RuntimeError(
            f"Cannot enforce saved-view defaults: {conflicts} user/page groups have "
            "multiple defaults. Resolve each owner's intended default before retrying; "
            "no saved views have been changed. Inspect with SELECT user_id, page, "
            "array_agg(id ORDER BY id) FROM saved_views WHERE is_default "
            "GROUP BY user_id, page HAVING count(*) > 1."
        )
    op.create_index(
        "uq_saved_views_user_page_default",
        "saved_views",
        ["user_id", "page"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_saved_views_user_page_default",
        table_name="saved_views",
        postgresql_where=sa.text("is_default"),
    )
    # ### end Alembic commands ###
