"""let a managed board bypass the clearance gate

Revision ID: 5dc82667db3b
Revises: 8c6534e680b5
Create Date: 2026-10-04 21:32:39.312440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5dc82667db3b'
down_revision: Union[str, None] = '8c6534e680b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_boards', sa.Column('bypass_sponsorship_filter', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managed_boards', 'bypass_sponsorship_filter')
    # ### end Alembic commands ###
