"""drop user_jobs.date_applied

Revision ID: 677b36b26ff5
Revises: 7d32a6ece505
Create Date: 2026-10-10 14:20:16.596276

The contract half of the change that made `applications` the only home of
the applied day: the board reads the application's day and no longer writes
or reads this column. Every image that names the column must be gone from the
fleet before this applies, because dropping it breaks any statement that
names it.

Nothing here can drop data. ck_user_jobs_date_applied_empty asserts the column
is NULL on every row. It is added NOT VALID (no scan) and then validated,
which scans user_jobs under SHARE UPDATE EXCLUSIVE: reads and writes continue.
If any row holds a day, VALIDATE raises, nothing is dropped, and the container
does not start. A rerun replaces the guard and validates again. Until the drop
commits, the guard also refuses a write of a day.

Production was emptied on 2026-10-10 at about 19:23 UTC, after every worker
reported release 54c0e931 (#937): 789 rows held a day, 0 after. 768 of them
repeated their application's day; 21 were "No Longer Interested" rows dated
by the old any-status stamp, with no application, and those days are gone.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "677b36b26ff5"
down_revision: Union[str, None] = "7d32a6ece505"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_GUARD = "ck_user_jobs_date_applied_empty"


def upgrade() -> None:
    with op.get_context().autocommit_block():
        # bd1e66f153c3's judgment: a start can afford a minute for the
        # transactions in flight, and past that the wait is not ending.
        op.execute("SET lock_timeout = '60s'")
        op.execute(f"ALTER TABLE user_jobs DROP CONSTRAINT IF EXISTS {_GUARD}")
        op.execute(
            f"ALTER TABLE user_jobs ADD CONSTRAINT {_GUARD} CHECK (date_applied IS NULL) NOT VALID"
        )
        op.execute(f"ALTER TABLE user_jobs VALIDATE CONSTRAINT {_GUARD}")
        op.execute("RESET lock_timeout")
    op.execute("SET LOCAL lock_timeout = '60s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_jobs", "date_applied")
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '60s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_jobs", sa.Column("date_applied", sa.DATE(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
