"""add managed board execution mode

Revision ID: 68622a4836a3
Revises: 68f3bdec787f
Create Date: 2026-09-11 20:03:20.614790

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "68622a4836a3"
down_revision: str | None = "68f3bdec787f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "managed_boards",
        sa.Column(
            "execution_mode",
            sa.Text(),
            server_default=sa.text("'managed_filter'"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "ck_managed_boards_execution_mode",
        "managed_boards",
        "execution_mode IN ('managed_filter', 'sponsor_filter_reuse')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_managed_boards_execution_mode", "managed_boards", type_="check")
    op.drop_column("managed_boards", "execution_mode")
    # ### end Alembic commands ###
