"""add managed boards foundation

Revision ID: 68f3bdec787f
Revises: f4597fad7cea
Create Date: 2026-09-11 19:14:52.997568

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "68f3bdec787f"
down_revision: str | None = "f4597fad7cea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "managed_boards",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column("sponsor_user_id", sa.BigInteger(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("prompt_hash", sa.Text(), nullable=False),
        sa.Column("requested_model", sa.Text(), nullable=False),
        sa.Column("on_ambiguous", sa.Text(), server_default=sa.text("'keep'"), nullable=False),
        sa.Column("fail_closed", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "criteria",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("published", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("revision", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("public_revision", sa.BigInteger(), nullable=True),
        sa.Column("projection_updated_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("published_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("unpublished_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "on_ambiguous IN ('keep', 'filter')", name="ck_managed_boards_on_ambiguous"
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name="ck_managed_boards_slug_lower_kebab"
        ),
        sa.CheckConstraint(
            "public_revision IS NULL OR public_revision >= 1",
            name="ck_managed_boards_public_revision_positive",
        ),
        sa.CheckConstraint(
            "(published AND published_at IS NOT NULL AND unpublished_at IS NULL AND public_revision IS NOT NULL) OR (NOT published)",
            name="ck_managed_boards_public_state",
        ),
        sa.CheckConstraint("revision >= 1", name="ck_managed_boards_revision_positive"),
        sa.ForeignKeyConstraint(["sponsor_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_managed_boards_slug"),
    )
    op.create_table(
        "managed_board_jobs",
        sa.Column("managed_board_id", sa.BigInteger(), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "projected_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sort_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("projection_revision", sa.BigInteger(), nullable=False),
        sa.Column("resolved_model", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["managed_board_id"], ["managed_boards.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("managed_board_id", "job_id"),
    )
    op.create_index(
        "idx_managed_board_jobs_newest",
        "managed_board_jobs",
        [
            "managed_board_id",
            sa.literal_column("sort_at DESC"),
            sa.literal_column("job_id DESC"),
        ],
        unique=False,
    )
    op.create_table(
        "managed_board_sources",
        sa.Column("managed_board_id", sa.BigInteger(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["managed_board_id"], ["managed_boards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source"], ["sources.name"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("managed_board_id", "source"),
    )
    op.create_index(
        "idx_managed_board_sources_source",
        "managed_board_sources",
        ["source", "managed_board_id"],
        unique=False,
    )
    op.add_column("api_usage", sa.Column("managed_board_id", sa.BigInteger(), nullable=True))
    op.create_index(
        "idx_api_usage_managed_board_created",
        "api_usage",
        ["managed_board_id", "created_at"],
        unique=False,
    )
    op.create_foreign_key(
        "api_usage_managed_board_id_fkey",
        "api_usage",
        "managed_boards",
        ["managed_board_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        "ck_api_usage_single_subject", "api_usage", "user_id IS NULL OR managed_board_id IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_api_usage_single_subject", "api_usage", type_="check")
    op.drop_constraint("api_usage_managed_board_id_fkey", "api_usage", type_="foreignkey")
    op.drop_index("idx_api_usage_managed_board_created", table_name="api_usage")
    op.drop_column("api_usage", "managed_board_id")
    op.drop_index("idx_managed_board_sources_source", table_name="managed_board_sources")
    op.drop_table("managed_board_sources")
    op.drop_index("idx_managed_board_jobs_newest", table_name="managed_board_jobs")
    op.drop_table("managed_board_jobs")
    op.drop_table("managed_boards")
    # ### end Alembic commands ###
