"""current event and match pointers on email_messages

Nullable and empty on arrival; the writers set them from the next deploy and
the backfill_mail_pointers task fills the rest. The indexes are built plainly:
email_messages held 78 MB of heap and 69,280 rows on 2026-10-10, and every
value is NULL at build time, so the SHARE lock lasts well under a second.

Revision ID: 6ba27711ec9e
Revises: 5a7c2e9d1b40
Create Date: 2026-10-10 00:53:45.230437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "6ba27711ec9e"
down_revision: Union[str, None] = "5a7c2e9d1b40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("email_messages", sa.Column("current_event_id", sa.BigInteger(), nullable=True))
    op.add_column("email_messages", sa.Column("current_match_id", sa.BigInteger(), nullable=True))
    op.create_index(
        "idx_email_messages_current_event",
        "email_messages",
        ["current_event_id"],
        unique=False,
        postgresql_where=sa.text("current_event_id IS NOT NULL"),
    )
    op.create_index(
        "idx_email_messages_current_match",
        "email_messages",
        ["current_match_id"],
        unique=False,
        postgresql_where=sa.text("current_match_id IS NOT NULL"),
    )
    op.create_foreign_key(
        "email_messages_current_event_id_fkey",
        "email_messages",
        "email_events",
        ["current_event_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "email_messages_current_match_id_fkey",
        "email_messages",
        "application_matches",
        ["current_match_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("email_messages_current_match_id_fkey", "email_messages", type_="foreignkey")
    op.drop_constraint("email_messages_current_event_id_fkey", "email_messages", type_="foreignkey")
    op.drop_index(
        "idx_email_messages_current_match",
        table_name="email_messages",
        postgresql_where=sa.text("current_match_id IS NOT NULL"),
    )
    op.drop_index(
        "idx_email_messages_current_event",
        table_name="email_messages",
        postgresql_where=sa.text("current_event_id IS NOT NULL"),
    )
    op.drop_column("email_messages", "current_match_id")
    op.drop_column("email_messages", "current_event_id")
    # ### end Alembic commands ###
