"""drop ai_prompts, ai_prompt_samples and unread batch and board columns

Revision ID: 72dc0fd47e51
Revises: c4dd7d081b39
Create Date: 2026-10-10 01:07:43.917065

The contract half of #846 and #854. Nothing reads any of these:

- ai_prompts, ai_prompt_samples and ai_batches.prompt_id: written by the
  batch runner until #846, read by nothing but the writer's own sample cap.
  Production on 2026-10-10: 15 prompts, 1,500 samples (1.1 MB together),
  prompt_id on 2,644 of 10,464 batches. The last write was 2026-10-10
  02:54 UTC, before #846 reached the fleet.
- managed_board_jobs.projection_revision and resolved_model: written by the
  projection rebuild until #854, read by nothing. 1,332 rows.
- app_config rows for embedding_visible_only (removed from the registry in
  #851) and managed_board_run_jobs_retention_days (removed earlier). No code
  reads either key; GET /admin/config would otherwise list them as values
  the registry does not describe.

These hold values, so no guard can prove them empty. The values are discarded
on purpose: nothing reads them, and the code that wrote them is gone. What
the guard in the rule protects against is an image that still names a
column; every image that did was off the fleet before this merged (checked
against worker_status.release and alembic_version).

Lock behaviour: one short transaction under lock_timeout. DROP TABLE and DROP
COLUMN take ACCESS EXCLUSIVE briefly and rewrite nothing. The FK from
ai_batches to ai_prompts is dropped first.

Downgrade recreates the tables and columns empty. It cannot restore the
values.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '72dc0fd47e51'
down_revision: Union[str, None] = 'c4dd7d081b39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '60s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_batches_prompt_id_fkey'), 'ai_batches', type_='foreignkey')
    op.drop_column('ai_batches', 'prompt_id')
    op.drop_index(op.f('idx_ai_prompt_samples_prompt'), table_name='ai_prompt_samples')
    op.drop_table('ai_prompt_samples')
    op.drop_index(op.f('idx_ai_prompts_purpose'), table_name='ai_prompts')
    op.drop_table('ai_prompts')
    op.drop_column('managed_board_jobs', 'projection_revision')
    op.drop_column('managed_board_jobs', 'resolved_model')
    # ### end Alembic commands ###
    op.execute(
        "DELETE FROM app_config WHERE key IN "
        "('embedding_visible_only', 'managed_board_run_jobs_retention_days')"
    )


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '60s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managed_board_jobs', sa.Column('resolved_model', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('managed_board_jobs', sa.Column('projection_revision', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('ai_batches', sa.Column('prompt_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_table('ai_prompts',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('prompt_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('first_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('batches', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_prompts_pkey')),
    sa.UniqueConstraint('prompt_hash', name=op.f('ai_prompts_prompt_hash_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_ai_prompts_purpose'), 'ai_prompts', ['purpose', 'last_seen_at'], unique=False)
    op.create_table('ai_prompt_samples',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('custom_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompts.id'], name=op.f('ai_prompt_samples_prompt_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_prompt_samples_pkey'))
    )
    op.create_index(op.f('idx_ai_prompt_samples_prompt'), 'ai_prompt_samples', ['prompt_id', 'id'], unique=False)
    op.create_foreign_key(op.f('ai_batches_prompt_id_fkey'), 'ai_batches', 'ai_prompts', ['prompt_id'], ['id'])
    # ### end Alembic commands ###
