"""record the question a verdict answered

Revision ID: 7ba8f26a74fd
Revises: 1afab52e064c
Create Date: 2026-10-04 21:11:43.049338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7ba8f26a74fd'
down_revision: Union[str, None] = '1afab52e064c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_queries', sa.Column('request_sha256', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_queries', 'request_sha256')
    # ### end Alembic commands ###
