"""drop inline review decision columns and the url-keyed indexes

Revision ID: 7ca95d34ef5f
Revises: f8dbf9b28085
Create Date: 2026-10-03 16:26:46.637767

The contract half of f8dbf9b28085. On 2026-10-03 production held 7,782,858
decisions, every one with url_id and body_id and none with an inline value
(pg_stats null_frac 1.0 for all twelve columns dropped here). The writer
stores only references since #753, and readers resolve only references since
the release before this one. Every image that still reads the inline columns
must be gone from the fleet before this applies: dropping a column breaks any
statement that names it.

Nothing here can drop data. ck_review_gate_decisions_references_only asserts
that every inline column is NULL and both references are present. It is added
NOT VALID (no scan) and then validated, which scans the table under SHARE
UPDATE EXCLUSIVE: reads and writes continue. If any row holds an inline value
or lacks a reference, VALIDATE raises, nothing is dropped, and the container
does not start. A rerun replaces the guard and validates again. Until the drop
commits, the guard also refuses a concurrent write of an inline value.

Lock behaviour, in order:
- ADD CONSTRAINT ... NOT VALID: ACCESS EXCLUSIVE, catalog only, under
  lock_timeout.
- VALIDATE the guard and the two foreign keys from f8dbf9b28085: SHARE UPDATE
  EXCLUSIVE on review_gate_decisions (ROW SHARE on the referenced table for a
  foreign key). Each is one pass over the 11.4 GB heap. None blocks a reader or
  the writer, but together they hold the schema lock for that long at startup.
- DROP INDEX CONCURRENTLY idx_review_gate_decisions_url_created (1,547,968,512
  bytes on 2026-10-03): SHARE UPDATE EXCLUSIVE.
- One short transaction: SET NOT NULL on url_id and body_id, which the
  validated guard proves without a scan (PostgreSQL 12+); drop
  uq_review_gate_decisions_task_url (1,566,302,208 bytes), which is a
  constraint and so cannot be dropped CONCURRENTLY; drop the twelve columns.
  This holds ACCESS EXCLUSIVE briefly and rewrites nothing. Index files are
  unlinked at commit.

The two indexes free 3,114,270,720 bytes. Dropping the columns frees no heap
space, because NULLs occupy none. The table shrinks only with a rewrite, and a
rewrite is not part of this migration.

The bounded migration operator (api.migrate_review_decisions) goes with the
columns: every mode read or wrote them. Downgrade adds the columns back empty
and rebuilds the indexes and constraints concurrently or NOT VALID followed by
VALIDATE. That is what the releases from #751 on need, because they read
references. An image older than #751 needs its inline values back: deploy the
#753 image and run its `restore` operator first.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7ca95d34ef5f'
down_revision: Union[str, None] = 'f8dbf9b28085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLE = 'review_gate_decisions'
_GUARD = 'ck_review_gate_decisions_references_only'
_INLINE = {
    'url': sa.Text(),
    'prompt_hash': sa.Text(),
    'stage': sa.Text(),
    'mode': sa.Text(),
    'action': sa.Text(),
    'reason': sa.Text(),
    'profile_id': sa.BigInteger(),
    'title': sa.Text(),
    'content_hash': sa.Text(),
    'policy_id': sa.BigInteger(),
    'policy': postgresql.JSONB(astext_type=sa.Text()),
    'evidence': postgresql.JSONB(astext_type=sa.Text()),
}
_INVALID = sa.text(
    "SELECT 1 FROM pg_index i JOIN pg_class c ON c.oid = i.indexrelid "
    "WHERE c.relname = :name AND NOT i.indisvalid"
)


def upgrade() -> None:
    with op.get_context().autocommit_block():
        # bd1e66f153c3's judgment: a start can afford a minute for the
        # transactions in flight, and past that the wait is not ending.
        op.execute("SET lock_timeout = '60s'")
        op.execute(f"ALTER TABLE {_TABLE} DROP CONSTRAINT IF EXISTS {_GUARD}")
        op.execute(
            f"ALTER TABLE {_TABLE} ADD CONSTRAINT {_GUARD} CHECK (url_id IS NOT NULL "
            "AND body_id IS NOT NULL AND "
            + " AND ".join(f"{column} IS NULL" for column in _INLINE)
            + ") NOT VALID"
        )
        for constraint in (_GUARD, 'fk_review_gate_decisions_url', 'fk_review_gate_decisions_body'):
            op.execute(f"ALTER TABLE {_TABLE} VALIDATE CONSTRAINT {constraint}")
        op.execute("DROP INDEX CONCURRENTLY IF EXISTS idx_review_gate_decisions_url_created")
        op.execute("RESET lock_timeout")
    op.execute("SET LOCAL lock_timeout = '60s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(_TABLE, 'url_id', existing_type=sa.BIGINT(), nullable=False)
    op.alter_column(_TABLE, 'body_id', existing_type=sa.BIGINT(), nullable=False)
    op.drop_constraint('uq_review_gate_decisions_task_url', _TABLE, type_='unique')
    op.drop_constraint('fk_review_gate_decisions_policy', _TABLE, type_='foreignkey')
    op.drop_constraint('ck_review_gate_decisions_shape', _TABLE, type_='check')
    op.drop_constraint('ck_review_gate_decisions_action', _TABLE, type_='check')
    op.drop_constraint(_GUARD, _TABLE, type_='check')
    for column in _INLINE:
        op.drop_column(_TABLE, column)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '60s'")
    # ### commands auto generated by Alembic - please adjust! ###
    # Adding a nullable column without a default rewrites nothing.
    for column, type_ in _INLINE.items():
        op.add_column(_TABLE, sa.Column(column, type_, nullable=True))
    op.alter_column(_TABLE, 'body_id', existing_type=sa.BIGINT(), nullable=True)
    op.alter_column(_TABLE, 'url_id', existing_type=sa.BIGINT(), nullable=True)
    op.create_foreign_key(
        'fk_review_gate_decisions_policy', _TABLE, 'review_gate_policies',
        ['policy_id'], ['id'], ondelete='RESTRICT', postgresql_not_valid=True,
    )
    op.execute(
        f"ALTER TABLE {_TABLE} ADD CONSTRAINT ck_review_gate_decisions_shape CHECK ("
        "(url IS NOT NULL OR url_id IS NOT NULL) AND (body_id IS NOT NULL OR "
        "(prompt_hash IS NOT NULL AND stage IS NOT NULL AND mode IS NOT NULL "
        "AND action IS NOT NULL AND title IS NOT NULL AND evidence IS NOT NULL))) NOT VALID"
    )
    op.execute(
        f"ALTER TABLE {_TABLE} ADD CONSTRAINT ck_review_gate_decisions_action "
        "CHECK (action IN ('skip','review')) NOT VALID"
    )
    # ### end Alembic commands ###
    with op.get_context().autocommit_block():
        op.execute("SET lock_timeout = '60s'")
        # Every new column is NULL, so this passes; it runs here, outside the
        # ACCESS EXCLUSIVE transaction, because it scans the table.
        op.execute(f"ALTER TABLE {_TABLE} VALIDATE CONSTRAINT ck_review_gate_decisions_action")
        for name, columns, unique in (
            ('idx_review_gate_decisions_url_created', ['url', 'created_at'], False),
            ('uq_review_gate_decisions_task_url', ['task_id', 'url'], True),
        ):
            # An interrupted build leaves an INVALID index that IF NOT EXISTS
            # would accept as finished.
            if op.get_bind().execute(_INVALID, {"name": name}).first():
                op.execute(f"DROP INDEX CONCURRENTLY {name}")
            op.create_index(
                name, _TABLE, columns, unique=unique,
                postgresql_concurrently=True, if_not_exists=True,
            )
        if not op.get_bind().execute(
            sa.text("SELECT 1 FROM pg_constraint WHERE conname = 'uq_review_gate_decisions_task_url'")
        ).first():
            op.execute(
                f"ALTER TABLE {_TABLE} ADD CONSTRAINT uq_review_gate_decisions_task_url "
                "UNIQUE USING INDEX uq_review_gate_decisions_task_url"
            )
        op.execute("RESET lock_timeout")
