"""count batch resumes apart from retries

Additive. A constant default is stored in the catalog, so the add rewrites
nothing. Existing rows start at 0, which undercounts resumes that already
happened and so leaves their budget where it was; no backfill, because on
2026-10-04 no pending, running or parked batch task in production was at the
cap (the two parked tasks were at attempts 1).

Revision ID: 8c6534e680b5
Revises: 7ba8f26a74fd
Create Date: 2026-10-04 21:29:03.818931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8c6534e680b5'
down_revision: Union[str, None] = '7ba8f26a74fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('batch_resumes', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'batch_resumes')
    # ### end Alembic commands ###
