"""user_source_groups and the views over a person's sources

Joining a bundle means following it: its members added later reach the
person too. A follow is a row here that points at the bundle.
`user_followed_sources` is every active member of every bundle a person
follows (a member whose source is switched off is not on offer).
`user_source_set` is a person's sources: their one-by-one picks in
`user_sources` plus what they follow, without repeats.

A predicate over many postings reads the two parts as two IN lists joined by
OR (core.store.PERSON_SOURCE), not the union: the planner guesses 200 rows
for a union's distinct sources and walks the jobs index once per source,
measured on production 2026-10-10 at 0.93 to 1.28 s against 0.37 to 0.40 s
for the OR form and 0.38 to 0.43 s for the picks table alone.

A new empty table and two views that only read; nothing is rewritten.

Revision ID: 98ace4b3fc55
Revises: 72dc0fd47e51
Create Date: 2026-10-10 00:58:32.479260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '98ace4b3fc55'
down_revision: Union[str, None] = '72dc0fd47e51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_source_groups',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_name'], ['source_groups.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_name')
    )
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE OR REPLACE VIEW user_followed_sources AS
        SELECT f.user_id, s.name AS source
        FROM user_source_groups f
        JOIN source_groups g ON g.name = f.group_name
        CROSS JOIN LATERAL unnest(g.members) AS m(name)
        JOIN sources s ON s.name = m.name AND s.active
        """
    )
    op.execute(
        """
        CREATE OR REPLACE VIEW user_source_set AS
        SELECT user_id, source FROM user_sources
        UNION
        SELECT user_id, source FROM user_followed_sources
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS user_source_set")
    op.execute("DROP VIEW IF EXISTS user_followed_sources")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_source_groups')
    # ### end Alembic commands ###
