"""user confirmed identities

Revision ID: a45f6ffe4306
Revises: d9f2c4b81e57
Create Date: 2026-09-03 18:59:44.355719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a45f6ffe4306'
down_revision: Union[str, None] = 'd9f2c4b81e57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('identities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_settings', sa.Column('identities_confirmed_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'identities_confirmed_at')
    op.drop_column('user_settings', 'identities')
    # ### end Alembic commands ###
