"""jobs.relisted_at

Revision ID: addd85bf1775
Revises: 7e2f9c4b1a63
Create Date: 2026-09-10 19:38:17.602086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'addd85bf1775'
down_revision: Union[str, None] = '7e2f9c4b1a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('relisted_at', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'relisted_at')
    # ### end Alembic commands ###
