"""group allowed models

Revision ID: b1cf341e5fcc
Revises: 28792f6f3930
Create Date: 2026-08-24 15:34:33.088692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b1cf341e5fcc'
down_revision: Union[str, None] = '28792f6f3930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_budgets', sa.Column('allowed_models', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_budgets', 'allowed_models')
    # ### end Alembic commands ###
