"""drop action_items and suggestion_responses

Every server has run 09397cf6c3d1's release since 2026-10-10 06:45 UTC, and
nothing has read or written either table since. Answers a person gave
through the old tables during the roll are copied to event_answers first,
idempotently; on 2026-10-10 there were none (suggestion_responses still held
its 8 copied rows, newest 2026-09-13, and action_items had no person's
closure). The asks themselves are derived when read and need no copy.

Revision ID: b223a0d76bc8
Revises: 09397cf6c3d1
Create Date: 2026-10-10 02:46:33.213291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b223a0d76bc8'
down_revision: Union[str, None] = '09397cf6c3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '60s'")
    op.execute(
        """
        INSERT INTO event_answers (event_id, question, answer, actor_user_id, created_at)
        SELECT sr.event_id, 'status', sr.response, sr.user_id, sr.created_at
        FROM suggestion_responses sr
        JOIN email_events e ON e.id = sr.event_id
        WHERE NOT EXISTS (
            SELECT 1 FROM event_answers ea
            WHERE ea.event_id = sr.event_id AND ea.question = 'status'
              AND ea.created_at = sr.created_at
        )
        ORDER BY sr.id
        """
    )
    # A closure by hand: no settling event, and not the old sweep's own
    # closure of an ask whose message had moved.
    op.execute(
        """
        INSERT INTO event_answers (event_id, question, answer, actor_user_id, note, created_at)
        SELECT ai.event_id, 'action', 'done', ai.user_id, ai.resolution, ai.resolved_at
        FROM action_items ai
        WHERE ai.event_id IS NOT NULL AND ai.resolved_at IS NOT NULL
          AND ai.resolved_by_event_id IS NULL
          AND ai.resolution IS DISTINCT FROM
              'the message this asked about is no longer part of this application'
          AND NOT EXISTS (
              SELECT 1 FROM event_answers ea
              WHERE ea.event_id = ai.event_id AND ea.question = 'action'
          )
        ORDER BY ai.id
        """
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_action_items_open'), table_name='action_items', postgresql_where='(resolved_at IS NULL)')
    op.drop_table('action_items')
    op.drop_index(op.f('idx_suggestion_responses_app'), table_name='suggestion_responses')
    op.drop_table('suggestion_responses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggestion_responses',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('suggested_status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('suggestion_responses_application_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('suggestion_responses_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('suggestion_responses_pkey'))
    )
    op.create_index(op.f('idx_suggestion_responses_app'), 'suggestion_responses', ['application_id', 'event_id'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('event_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('kind', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('due_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('resolution', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolved_by_event_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('action_items_application_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['email_events.id'], name=op.f('action_items_event_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_event_id'], ['email_events.id'], name=op.f('action_items_resolved_by_event_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('action_items_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('action_items_pkey'))
    )
    op.create_index(op.f('idx_action_items_open'), 'action_items', ['user_id', 'due_at'], unique=False, postgresql_where='(resolved_at IS NULL)')
    # ### end Alembic commands ###
