"""allow unknown embedding input usage

Revision ID: b48a878a0be1
Revises: 04648af4207c
Create Date: 2026-09-09 08:00:15.965331

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "b48a878a0be1"
down_revision: Union[str, None] = "04648af4207c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "job_embeddings",
        "input_tokens",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "job_embeddings",
        "input_tokens",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text("0"),
    )
    # ### end Alembic commands ###
