"""job_listing_events replaces jobs.relisted_at

Revision ID: b64dadabb22d
Revises: addd85bf1775
Create Date: 2026-09-10 21:53:35.618003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b64dadabb22d'
down_revision: Union[str, None] = 'addd85bf1775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_listing_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('listed', sa.Boolean(), nullable=False),
    sa.Column('at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_job_listing_events_latest', 'job_listing_events', ['job_id', sa.literal_column('id DESC')], unique=False)
    op.drop_column('jobs', 'relisted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('relisted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index('idx_job_listing_events_latest', table_name='job_listing_events')
    op.drop_table('job_listing_events')
    # ### end Alembic commands ###
