"""let managed_board_jobs.projection_revision be null

Revision ID: c4dd7d081b39
Revises: 5460c0343629
Create Date: 2026-10-10 00:16:21.747225

The expand half of dropping managed_board_jobs.projection_revision and
resolved_model. Nothing reads either column. This release stops writing them,
so projection_revision must accept NULL while older images still write it.
The next release drops both.

DROP NOT NULL is a catalog change: ACCESS EXCLUSIVE briefly, no scan, no
rewrite (1,332 rows on 2026-10-10).

Downgrade fills NULLs from managed_boards.revision, which is the value the
writer stored, before restoring NOT NULL.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c4dd7d081b39'
down_revision: Union[str, None] = '5460c0343629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '60s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managed_board_jobs', 'projection_revision',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("SET LOCAL lock_timeout = '60s'")
    op.execute(
        "UPDATE managed_board_jobs mj SET projection_revision = b.revision "
        "FROM managed_boards b WHERE b.id = mj.managed_board_id "
        "AND mj.projection_revision IS NULL"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('managed_board_jobs', 'projection_revision',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
