"""bypass sponsorship filter

Revision ID: c79027fe8552
Revises: 77778af0515d
Create Date: 2026-08-23 23:56:26.921993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c79027fe8552'
down_revision: Union[str, None] = '77778af0515d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('bypass_sponsorship_filter', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'bypass_sponsorship_filter')
    # ### end Alembic commands ###
