"""listing payload references

Revision ID: cd26607aae44
Revises: f8dbf9b28085
Create Date: 2026-10-03 16:22:32.832736

listings held about 650k rows on 2026-10-03, with 1.3 GB of TOAST for the
description and raw columns (about 595 MB and 630 MB compressed, from a 5%
sample). These columns let a field be held by reference to a verified bundle
object (core.listing_payloads). This writes no data: the writer that fills them
ships in a later release, and the backfill is api.migrate_listings.

Every change is additive. Adding a nullable column without a default rewrites
nothing. Both checks are NOT VALID so adding them scans nothing; every existing
row satisfies them because all six columns are NULL.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cd26607aae44'
down_revision: Union[str, None] = 'f8dbf9b28085'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Each ALTER takes a brief ACCESS EXCLUSIVE lock on the live table; ingest
    # writes it every few seconds, so a start waits rather than queueing them.
    op.execute("SET LOCAL lock_timeout = '60s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('description_sha256', sa.LargeBinary(), nullable=True))
    op.add_column('listings', sa.Column('description_object', sa.LargeBinary(), nullable=True))
    op.add_column('listings', sa.Column('description_object_size', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('raw_sha256', sa.LargeBinary(), nullable=True))
    op.add_column('listings', sa.Column('raw_object', sa.LargeBinary(), nullable=True))
    op.add_column('listings', sa.Column('raw_object_size', sa.Integer(), nullable=True))
    op.execute(
        "ALTER TABLE listings ADD CONSTRAINT ck_listings_description_reference CHECK ("
        "(description_sha256 IS NULL) = (description_object IS NULL) AND (description_object IS NULL) = (description_object_size IS NULL)) NOT VALID"
    )
    op.execute(
        "ALTER TABLE listings ADD CONSTRAINT ck_listings_raw_reference CHECK ("
        "(raw_sha256 IS NULL) = (raw_object IS NULL) AND (raw_object IS NULL) = (raw_object_size IS NULL)) NOT VALID"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_listings_raw_reference', 'listings', type_='check')
    op.drop_constraint('ck_listings_description_reference', 'listings', type_='check')
    op.drop_column('listings', 'raw_object_size')
    op.drop_column('listings', 'raw_object')
    op.drop_column('listings', 'raw_sha256')
    op.drop_column('listings', 'description_object_size')
    op.drop_column('listings', 'description_object')
    op.drop_column('listings', 'description_sha256')
    # ### end Alembic commands ###
