"""share immutable review policy snapshots

Revision ID: d2c923541eaa
Revises: 01a2e66a5929
Create Date: 2026-10-03 03:29:31.792161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd2c923541eaa'
down_revision: Union[str, None] = '01a2e66a5929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_gate_policies',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('digest', sa.LargeBinary(), nullable=False),
    sa.Column('policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest')
    )
    op.add_column('review_gate_decisions', sa.Column('policy_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_review_gate_decisions_policy', 'review_gate_decisions', 'review_gate_policies', ['policy_id'], ['id'], ondelete='RESTRICT', postgresql_not_valid=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_review_gate_decisions_policy', 'review_gate_decisions', type_='foreignkey')
    op.drop_column('review_gate_decisions', 'policy_id')
    op.drop_table('review_gate_policies')
    # ### end Alembic commands ###
