"""worker_status reports every task it holds

Revision ID: d71ea321d632
Revises: 63f0ea027862
Create Date: 2026-10-10 21:58:52.969390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "d71ea321d632"
down_revision: Union[str, None] = "63f0ea027862"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worker_status",
        sa.Column(
            "current_task_ids",
            postgresql.ARRAY(sa.BigInteger()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    op.add_column("worker_status", sa.Column("task_limit", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker_status", "task_limit")
    op.drop_column("worker_status", "current_task_ids")
    # ### end Alembic commands ###
