"""source_observations

What each source said about each posting, appended when it changed (phase 3,
docs/agents/architecture-migration.md). A new empty table, so its indexes are
built plainly and its foreign key validates nothing.

Revision ID: db0c14af6775
Revises: 95018279350d
Create Date: 2026-10-10 00:21:21.830954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'db0c14af6775'
down_revision: Union[str, None] = '95018279350d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_observations',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('appeared', 'reappeared', 'filtered', 'unlisted', 'not_listed')", name='ck_source_observations_kind'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_observations_by_job', 'source_observations', ['job_id', 'source', sa.literal_column('id DESC')], unique=False)
    op.create_index('idx_source_observations_by_source', 'source_observations', ['source', 'job_id', sa.literal_column('id DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_source_observations_by_source', table_name='source_observations')
    op.drop_index('idx_source_observations_by_job', table_name='source_observations')
    op.drop_table('source_observations')
    # ### end Alembic commands ###
