"""ai_queries: adopted from core/store.py, plus the board's index-only reads

Revision ID: f3a4b5c6d7e8
Revises: e2f3a4b5c6d7
Create Date: 2026-09-04

ai_queries was the last table created outside alembic: core/store.py ran
its own CREATE TABLE IF NOT EXISTS at import, and env.py told the drift
check to look away from it. So the model could not describe it, a column
had to be added in two places (d5e2a91c7f38 guards on the table existing
for exactly that reason), and "the schema is the migrations" was true of
every table but the largest one.

Every statement here is IF NOT EXISTS, so on production, where the table
and its thirteen indexes already exist, the revision creates nothing but
the two new indexes and sets the autovacuum thresholds. On a fresh database
it builds the table as production has it. Downgrade drops only what this
revision added: the table holds every paid AI verdict, and adopting it does
not make it alembic's to drop.

The two INCLUDE indexes serve the board's latest-verdict-per-url reads as
index-only scans. Measured on a copy of production (150,454 rows):

    DISTINCT ON (url, check_type) over closed/clearance rows
        before: Unique <- Sort <- Seq Scan            1157 to 1310 ms
        after:  Unique <- Index Only Scan, 0 heap fetches   52 to 62 ms
    DISTINCT ON (url, prompt_hash) over custom rows            21 ms

Without INCLUDE (status) the planner keeps the seq scan: the predicate
keeps 54% of the table, and at stock random_page_cost the heap fetches
cost more than sorting. With it there are no heap fetches to cost.

The gain is bimodal. With the visibility map cold the planner goes back to
the seq scan and sort at 1.2 s; nothing in between. The table takes 44%
updates (150,912 inserts, 66,916 updates), which dirty the map, and the
stock autovacuum thresholds wait for 20% of the table to go dead before
acting. The per-table settings keep the map warm by construction.
Heap Fetches in EXPLAIN ANALYZE is the early warning if that stops holding.

Build time on that copy: 1.3 s and 0.6 s, under a write lock on ai_queries.
"""

from alembic import op

revision = "f3a4b5c6d7e8"
down_revision = "e2f3a4b5c6d7"
branch_labels = None
depends_on = None

_BTREE = {
    "idx_ai_queries_batch": "(batch_id)",
    "idx_ai_queries_url": "(url)",
    "idx_ai_queries_url_check": "(url, check_type)",
    "idx_ai_queries_status": "(status)",
    "idx_ai_queries_check_type": "(check_type)",
    "idx_ai_queries_created_at": "(created_at)",
    "idx_ai_queries_prompt_hash": "(check_type, prompt_hash)",
    "idx_ai_queries_cost_created": "(created_at) WHERE cost_usd IS NOT NULL",
    "idx_ai_queries_latest_verdict": (
        "(url, check_type, id DESC) INCLUDE (status) "
        "WHERE check_type IN ('closed', 'clearance') AND status IN ('passed', 'rejected')"
    ),
    "idx_ai_queries_latest_custom": (
        "(url, prompt_hash, id DESC) INCLUDE (status) "
        "WHERE check_type = 'custom' AND status IN ('passed', 'rejected')"
    ),
}
_TRGM = ("url", "company", "job_title", "reason")


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS ai_queries (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            config_name TEXT,
            url TEXT,
            check_type TEXT,
            status TEXT,
            reason TEXT,
            model TEXT,
            reasoning_effort TEXT,
            filter_name TEXT,
            prompt_hash TEXT,
            company TEXT,
            job_title TEXT,
            instructions TEXT,
            input_content TEXT,
            parsed_json TEXT,
            prompt_tokens BIGINT,
            completion_tokens BIGINT,
            total_tokens BIGINT,
            cached_tokens BIGINT,
            reasoning_tokens BIGINT,
            duration_ms BIGINT,
            error TEXT,
            cost_usd NUMERIC(12, 6),
            worker TEXT,
            batch_id TEXT
        )
        """
    )
    for name, body in _BTREE.items():
        op.execute(f"CREATE INDEX IF NOT EXISTS {name} ON ai_queries {body}")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    for col in _TRGM:
        op.execute(
            f"CREATE INDEX IF NOT EXISTS idx_ai_queries_{col}_trgm "
            f"ON ai_queries USING gin ({col} gin_trgm_ops)"
        )
    op.execute(
        "ALTER TABLE ai_queries SET ("
        "autovacuum_vacuum_scale_factor = 0.02, "
        "autovacuum_vacuum_insert_scale_factor = 0.02, "
        "autovacuum_analyze_scale_factor = 0.01)"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE ai_queries RESET ("
        "autovacuum_vacuum_scale_factor, "
        "autovacuum_vacuum_insert_scale_factor, "
        "autovacuum_analyze_scale_factor)"
    )
    op.execute("DROP INDEX IF EXISTS idx_ai_queries_latest_custom")
    op.execute("DROP INDEX IF EXISTS idx_ai_queries_latest_verdict")
