"""add user job working set foundation

Revision ID: f4597fad7cea
Revises: b64dadabb22d
Create Date: 2026-09-11 17:27:51.893043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "f4597fad7cea"
down_revision: Union[str, None] = "b64dadabb22d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_job_working_set",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("job_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "job_id"),
    )
    op.create_index(
        "idx_user_job_working_set_job", "user_job_working_set", ["job_id"], unique=False
    )
    op.add_column(
        "user_jobs",
        sa.Column("person_touched_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_jobs", "person_touched_at")
    op.drop_index("idx_user_job_working_set_job", table_name="user_job_working_set")
    op.drop_table("user_job_working_set")
    # ### end Alembic commands ###
