"""store review decision bodies once

Revision ID: f8dbf9b28085
Revises: 221f5df878c9
Create Date: 2026-10-03 12:31:06.687399

review_gate_decisions was 13.6 GB for 7.6M rows on 2026-10-03, growing about
620k rows a day, while 2026-10-02's 570,747 rows held only 38,017 distinct
decision bodies. This adds the shared body and URL tables and the references
to them. It writes no data: the writer that fills the references ships in a
later release, and the backfill is api.migrate_review_decisions.

Relaxing NOT NULL on the inline columns is the non-additive part. No writer in
this release stores NULL there, and ck_review_gate_decisions_shape keeps the
guarantee those NOT NULLs gave: every row has its URL and its body, inline or
by reference. The check and both foreign keys are NOT VALID so adding them
scans nothing; they bind every row written or updated from here on, and every
existing row satisfies them because it is fully inline.

The two indexes are built CONCURRENTLY, as in bd1e66f153c3: a plain build
holds SHARE on the table for two passes over its 9.8 GB heap and every
admission would wait behind it. Building on a column that is NULL everywhere
cannot fail a uniqueness check.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f8dbf9b28085'
down_revision: Union[str, None] = '221f5df878c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_INDEXES = (
    ('idx_review_gate_decisions_url_id', ['url_id'], False),
    ('uq_review_gate_decisions_task_url_id', ['task_id', 'url_id'], True),
)
_INVALID = sa.text(
    "SELECT 1 FROM pg_index i JOIN pg_class c ON c.oid = i.indexrelid "
    "WHERE c.relname = :name AND NOT i.indisvalid"
)


def upgrade() -> None:
    # Each ALTER takes a brief ACCESS EXCLUSIVE lock on the live table.
    op.execute("SET LOCAL lock_timeout = '60s'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_gate_urls',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('review_gate_decision_bodies',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('digest', sa.LargeBinary(), nullable=False),
    sa.Column('prompt_hash', sa.Text(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('policy_id', sa.BigInteger(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("action IN ('skip','review')", name='ck_review_gate_decision_bodies_action'),
    sa.ForeignKeyConstraint(['policy_id'], ['review_gate_policies.id'], name='fk_review_gate_decision_bodies_policy', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest')
    )
    op.add_column('review_gate_decisions', sa.Column('url_id', sa.BigInteger(), nullable=True))
    op.add_column('review_gate_decisions', sa.Column('body_id', sa.BigInteger(), nullable=True))
    op.alter_column('review_gate_decisions', 'url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('review_gate_decisions', 'prompt_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('review_gate_decisions', 'stage',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('review_gate_decisions', 'mode',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('review_gate_decisions', 'action',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('review_gate_decisions', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('review_gate_decisions', 'evidence',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_foreign_key('fk_review_gate_decisions_url', 'review_gate_decisions', 'review_gate_urls', ['url_id'], ['id'], ondelete='RESTRICT', postgresql_not_valid=True)
    op.create_foreign_key('fk_review_gate_decisions_body', 'review_gate_decisions', 'review_gate_decision_bodies', ['body_id'], ['id'], ondelete='RESTRICT', postgresql_not_valid=True)
    op.execute(
        "ALTER TABLE review_gate_decisions ADD CONSTRAINT ck_review_gate_decisions_shape CHECK ("
        "(url IS NOT NULL OR url_id IS NOT NULL) AND (body_id IS NOT NULL OR "
        "(prompt_hash IS NOT NULL AND stage IS NOT NULL AND mode IS NOT NULL "
        "AND action IS NOT NULL AND title IS NOT NULL AND evidence IS NOT NULL))) NOT VALID"
    )
    # ### end Alembic commands ###
    with op.get_context().autocommit_block():
        # A judgment, not a measurement, as in bd1e66f153c3: a start can afford
        # a minute for the transactions in flight, and past that it is not ending.
        op.execute("SET lock_timeout = '60s'")
        for name, columns, unique in _INDEXES:
            if op.get_bind().execute(_INVALID, {"name": name}).first():
                op.execute(f"DROP INDEX CONCURRENTLY {name}")
            op.create_index(
                name,
                'review_gate_decisions',
                columns,
                unique=unique,
                postgresql_concurrently=True,
                if_not_exists=True,
            )
        op.execute("RESET lock_timeout")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Restoring NOT NULL fails while any row is reference-only: run
    # api.migrate_review_decisions restore over every row first.
    with op.get_context().autocommit_block():
        for name, _, _ in _INDEXES:
            op.drop_index(name, table_name='review_gate_decisions', postgresql_concurrently=True, if_exists=True)
    op.drop_constraint('ck_review_gate_decisions_shape', 'review_gate_decisions', type_='check')
    op.drop_constraint('fk_review_gate_decisions_body', 'review_gate_decisions', type_='foreignkey')
    op.drop_constraint('fk_review_gate_decisions_url', 'review_gate_decisions', type_='foreignkey')
    op.alter_column('review_gate_decisions', 'evidence',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('review_gate_decisions', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('review_gate_decisions', 'action',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('review_gate_decisions', 'mode',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('review_gate_decisions', 'stage',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('review_gate_decisions', 'prompt_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('review_gate_decisions', 'url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('review_gate_decisions', 'body_id')
    op.drop_column('review_gate_decisions', 'url_id')
    op.drop_table('review_gate_decision_bodies')
    op.drop_table('review_gate_urls')
    # ### end Alembic commands ###
