"""task heartbeat and attempts

Revision ID: fbd5cb103b52
Revises: 366160ace55b
Create Date: 2026-08-24 02:41:37.712938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fbd5cb103b52'
down_revision: Union[str, None] = '366160ace55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('attempts', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('tasks', sa.Column('last_heartbeat', postgresql.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'last_heartbeat')
    op.drop_column('tasks', 'attempts')
    # ### end Alembic commands ###
