"""share immutable query instruction text

Revision ID: fc5431a0bb93
Revises: 01a2e66a5929
Create Date: 2026-10-03 03:33:41.245589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc5431a0bb93'
down_revision: Union[str, None] = '01a2e66a5929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_instruction_texts',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.add_column('ai_queries', sa.Column('instructions_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_ai_queries_instructions_id', 'ai_queries', 'ai_instruction_texts', ['instructions_id'], ['id'], postgresql_not_valid=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ai_queries_instructions_id', 'ai_queries', type_='foreignkey')
    op.drop_column('ai_queries', 'instructions_id')
    op.drop_table('ai_instruction_texts')
    # ### end Alembic commands ###
