from __future__ import annotations

import atexit
import datetime
import os
from typing import Any, Dict, List, Optional

import dotenv
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

dotenv.load_dotenv()

DATABASE_URL = os.environ["DATABASE_URL"]

_INSERT_COLUMNS = [
    "created_at",
    "config_name",
    "url",
    "check_type",
    "status",
    "reason",
    "model",
    "reasoning_effort",
    "filter_name",
    "prompt_hash",
    "company",
    "job_title",
    "instructions",
    "input_content",
    "parsed_json",
    "prompt_tokens",
    "completion_tokens",
    "total_tokens",
    "cached_tokens",
    "reasoning_tokens",
    "duration_ms",
    "error",
]

_pool = ConnectionPool(
    DATABASE_URL,
    min_size=1,
    max_size=10,
    kwargs={"row_factory": dict_row},
    open=True,
)
atexit.register(_pool.close)

# Read-through caches populated by prefetch() to avoid a network round-trip per
# url. Each maps url -> latest decided row (or None for a confirmed miss). Only
# `status` is read off these rows, so the heavy text columns are left out.
_latest_cache: Dict[str, Dict[str, Optional[Dict[str, Any]]]] = {}
_custom_cache: Dict[str, Dict[str, Optional[Dict[str, Any]]]] = {}

# Heavy text columns no caller reads off a verdict row; omitted to save bandwidth
# and filled back as None so a cached row keeps the same shape as a full row.
_PREFETCH_OMIT = ("input_content", "instructions", "parsed_json")
_PREFETCH_COLS = ["id"] + [c for c in _INSERT_COLUMNS if c not in _PREFETCH_OMIT]


def _prefetch_row(r: Dict[str, Any]) -> Dict[str, Any]:
    d = dict(r)
    for c in _PREFETCH_OMIT:
        d[c] = None
    return d


def prefetch(
    urls: List[str],
    check_types: tuple = ("closed", "clearance"),
    prompt_hashes: tuple = (),
) -> None:
    """Bulk-load latest-decided verdicts for a batch of urls into the caches.

    One query per check_type / prompt_hash instead of one per url, so the
    per-job cache lookups become in-memory hits.
    """
    unique = list({u for u in urls if u})
    if not unique:
        return
    cols = ", ".join(_PREFETCH_COLS)
    with _pool.connection() as conn:
        for check_type in check_types:
            rows = conn.execute(
                f"SELECT DISTINCT ON (url) {cols} FROM ai_queries "
                "WHERE url = ANY(%s) AND check_type = %s "
                "AND status IN ('passed', 'rejected') ORDER BY url, id DESC",
                (unique, check_type),
            ).fetchall()
            found = {r["url"]: _prefetch_row(r) for r in rows}
            for u in unique:
                _latest_cache.setdefault(u, {})[check_type] = found.get(u)
        for prompt_hash in prompt_hashes:
            rows = conn.execute(
                f"SELECT DISTINCT ON (url) {cols} FROM ai_queries "
                "WHERE url = ANY(%s) AND check_type = 'custom' AND prompt_hash = %s "
                "AND status IN ('passed', 'rejected') ORDER BY url, id DESC",
                (unique, prompt_hash),
            ).fetchall()
            found = {r["url"]: _prefetch_row(r) for r in rows}
            for u in unique:
                _custom_cache.setdefault(u, {})[prompt_hash] = found.get(u)


def init_db() -> None:
    with _pool.connection() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS ai_queries (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at TEXT NOT NULL,
                config_name TEXT,
                url TEXT,
                check_type TEXT,
                status TEXT,
                reason TEXT,
                model TEXT,
                reasoning_effort TEXT,
                filter_name TEXT,
                prompt_hash TEXT,
                company TEXT,
                job_title TEXT,
                instructions TEXT,
                input_content TEXT,
                parsed_json TEXT,
                prompt_tokens BIGINT,
                completion_tokens BIGINT,
                total_tokens BIGINT,
                cached_tokens BIGINT,
                reasoning_tokens BIGINT,
                duration_ms BIGINT,
                error TEXT
            )
            """
        )
        for stmt in (
            "CREATE INDEX IF NOT EXISTS idx_ai_queries_url ON ai_queries(url)",
            "CREATE INDEX IF NOT EXISTS idx_ai_queries_url_check ON ai_queries(url, check_type)",
            "CREATE INDEX IF NOT EXISTS idx_ai_queries_status ON ai_queries(status)",
            "CREATE INDEX IF NOT EXISTS idx_ai_queries_check_type ON ai_queries(check_type)",
            "CREATE INDEX IF NOT EXISTS idx_ai_queries_created_at ON ai_queries(created_at)",
            "CREATE INDEX IF NOT EXISTS idx_ai_queries_prompt_hash ON ai_queries(check_type, prompt_hash)",
        ):
            conn.execute(stmt)


def add_ai_result(
    url: str,
    status: str,
    reason: str = "",
    check_type: str = "",
    prompt_tokens: Optional[int] = None,
    completion_tokens: Optional[int] = None,
    total_tokens: Optional[int] = None,
    cached_tokens: Optional[int] = None,
    reasoning_tokens: Optional[int] = None,
    model: Optional[str] = None,
    reasoning_effort: Optional[str] = None,
    filter_name: Optional[str] = None,
    prompt_hash: Optional[str] = None,
    company: Optional[str] = None,
    job_title: Optional[str] = None,
    instructions: Optional[str] = None,
    input_content: Optional[str] = None,
    parsed_json: Optional[str] = None,
    duration_ms: Optional[int] = None,
    error: Optional[str] = None,
) -> None:
    row = {
        "created_at": datetime.datetime.now().isoformat(),
        "config_name": os.environ.get("CONFIG_NAME"),
        "url": url,
        "check_type": check_type,
        "status": status,
        "reason": reason,
        "model": model,
        "reasoning_effort": reasoning_effort,
        "filter_name": filter_name,
        "prompt_hash": prompt_hash,
        "company": company,
        "job_title": job_title,
        "instructions": instructions,
        "input_content": input_content,
        "parsed_json": parsed_json,
        "prompt_tokens": prompt_tokens,
        "completion_tokens": completion_tokens,
        "total_tokens": total_tokens,
        "cached_tokens": cached_tokens,
        "reasoning_tokens": reasoning_tokens,
        "duration_ms": duration_ms,
        "error": error,
    }
    columns = ", ".join(_INSERT_COLUMNS)
    placeholders = ", ".join(f"%({c})s" for c in _INSERT_COLUMNS)
    with _pool.connection() as conn:
        conn.execute(
            f"INSERT INTO ai_queries ({columns}) VALUES ({placeholders})", row
        )
    sub = _latest_cache.get(url)
    if sub is not None:
        sub.pop(check_type, None)
    if check_type == "custom" and prompt_hash is not None:
        csub = _custom_cache.get(url)
        if csub is not None:
            csub.pop(prompt_hash, None)


def get_ai_result(url: str) -> Optional[Dict[str, Any]]:
    with _pool.connection() as conn:
        row = conn.execute(
            "SELECT * FROM ai_queries WHERE url = %s ORDER BY id DESC LIMIT 1", (url,)
        ).fetchone()
    return dict(row) if row else None


def get_latest(url: str, check_type: str) -> Optional[Dict[str, Any]]:
    """Latest *decided* (passed/rejected) result for a url+check_type.

    Ignores 'failed' rows so failed checks are retried rather than cached.
    """
    sub = _latest_cache.get(url)
    if sub is not None and check_type in sub:
        return sub[check_type]
    with _pool.connection() as conn:
        row = conn.execute(
            "SELECT * FROM ai_queries WHERE url = %s AND check_type = %s "
            "AND status IN ('passed', 'rejected') ORDER BY id DESC LIMIT 1",
            (url, check_type),
        ).fetchone()
    return dict(row) if row else None


def get_custom_result(url: str, prompt_hash: str) -> Optional[Dict[str, Any]]:
    """Latest decided custom result for a url under a specific filter (by hash)."""
    sub = _custom_cache.get(url)
    if sub is not None and prompt_hash in sub:
        return sub[prompt_hash]
    with _pool.connection() as conn:
        row = conn.execute(
            "SELECT * FROM ai_queries WHERE url = %s AND check_type = 'custom' "
            "AND prompt_hash = %s AND status IN ('passed', 'rejected') "
            "ORDER BY id DESC LIMIT 1",
            (url, prompt_hash),
        ).fetchone()
    return dict(row) if row else None


def get_content(url: str) -> Optional[str]:
    """Most recent non-empty raw scraped content stored for a url.

    Excludes 'custom' rows: those store the wrapped _build_custom_input() text
    (company/title prefix), not raw page content, so reusing them would re-wrap
    the content on every subsequent custom filter.
    """
    with _pool.connection() as conn:
        row = conn.execute(
            "SELECT input_content FROM ai_queries WHERE url = %s "
            "AND check_type != 'custom' "
            "AND input_content IS NOT NULL AND input_content != '' "
            "ORDER BY id DESC LIMIT 1",
            (url,),
        ).fetchone()
    return row["input_content"] if row else None


def get_prelim_passed_urls() -> List[str]:
    """URLs whose latest closed AND latest clearance checks both passed."""
    with _pool.connection() as conn:
        rows = conn.execute(
            """
            SELECT url FROM ai_queries a
              WHERE check_type = 'closed' AND status = 'passed'
                AND id = (SELECT MAX(id) FROM ai_queries b
                          WHERE b.url = a.url AND b.check_type = 'closed')
            INTERSECT
            SELECT url FROM ai_queries a
              WHERE check_type = 'clearance' AND status = 'passed'
                AND id = (SELECT MAX(id) FROM ai_queries b
                          WHERE b.url = a.url AND b.check_type = 'clearance')
            """
        ).fetchall()
    return [r["url"] for r in rows]


def is_prelim_rejected(url: str) -> bool:
    """Rejected by a prompt-independent check (closed or clearance)."""
    closed = get_latest(url, "closed")
    if closed and closed["status"] == "rejected":
        return True
    clearance = get_latest(url, "clearance")
    return bool(clearance and clearance["status"] == "rejected")


def is_url_rejected(url: str) -> bool:
    result = get_ai_result(url)
    return result is not None and result.get("status") == "rejected"


def is_url_passed(url: str) -> bool:
    result = get_ai_result(url)
    return result is not None and result.get("status") == "passed"


def is_url_failed(url: str) -> bool:
    result = get_ai_result(url)
    return result is not None and result.get("status") == "failed"


def _latest_per_url_where(condition: str, params: tuple) -> List[Dict[str, Any]]:
    with _pool.connection() as conn:
        rows = conn.execute(
            "SELECT * FROM ai_queries q WHERE id = "
            "(SELECT MAX(id) FROM ai_queries WHERE url = q.url) "
            f"AND {condition}",
            params,
        ).fetchall()
    return [dict(row) for row in rows]


def get_all_failed_jobs() -> List[Dict[str, Any]]:
    return _latest_per_url_where("status = %s", ("failed",))


def get_all_custom_filter_jobs() -> List[Dict[str, Any]]:
    return _latest_per_url_where("check_type = %s", ("custom",))


init_db()
