"""Publish the extension's bundled recipe tables to the API's recipe store.

Reads extension/ats/*.js (each `window.__jtATS = [ {...} ];`, generated by
tools/convert_ats_config.py), validates each table the way the API does and
writes it as the current revision for its adapter. Runs against DATABASE_URL
from the environment or .env, so it is the operator's tool, run by hand:

    .venv/bin/python tools/publish_recipes.py            # every table
    .venv/bin/python tools/publish_recipes.py workday    # one adapter
    .venv/bin/python tools/publish_recipes.py --dry-run  # validate only

A republish of an unchanged table is the same revision and changes nothing.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from api import extension_recipes  # noqa: E402

ATS = ROOT / "extension" / "ats"
PREFIX = re.compile(r"^window\.__jtATS\s*=\s*", re.M)


def tables() -> dict[str, dict]:
    out: dict[str, dict] = {}
    for path in sorted(ATS.glob("*.js")):
        text = path.read_text()
        match = PREFIX.search(text)
        if not match:
            raise SystemExit(f"{path.name}: no window.__jtATS assignment")
        body = text[match.end() :].strip().rstrip(";")
        configs = json.loads(body)
        for cfg in configs:
            out[cfg["name"].lower()] = cfg
    return out


def main(argv: list[str]) -> int:
    dry = "--dry-run" in argv
    wanted = {a.lower() for a in argv if not a.startswith("--")}
    who = os.environ.get("USER", "publish_recipes")
    for adapter, cfg in tables().items():
        if wanted and adapter not in wanted:
            continue
        raw = extension_recipes.validate(adapter, cfg)
        revision = extension_recipes.revision_of(raw)
        if dry:
            print(f"{adapter}: valid, {len(raw):,} bytes, revision {revision[:12]}")
            continue
        extension_recipes.publish(adapter, cfg, who)
        print(f"{adapter}: published {len(raw):,} bytes as {revision[:12]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
